import { ModelCategory } from './models'

export interface Category {
  id: ModelCategory
  label: string
  emoji: string
  description: string
  keywords: string[]
}

export const CATEGORIES: Category[] = [
  {
    id: 'coding',
    label: 'Coding',
    emoji: '</>',
    description: 'Programacion y desarrollo de software',
    keywords: [
      'codigo', 'code', 'coding', 'programar', 'programacion', 'programming',
      'javascript', 'python', 'typescript', 'java', 'rust', 'go', 'c++',
      'bug', 'debug', 'debugar', 'error', 'funcion', 'function', 'clase', 'class',
      'api', 'backend', 'frontend', 'fullstack', 'web', 'app', 'aplicacion',
      'software', 'desarrollo', 'developer', 'script', 'automatizar', 'automate',
      'refactorizar', 'refactor', 'tests', 'testing', 'unittest', 'algoritmo',
      'algorithm', 'github', 'git', 'repositorio', 'repo', 'deploy', 'devops',
      'base de datos', 'database', 'sql', 'nosql', 'mongodb', 'postgres',
      'react', 'nextjs', 'vue', 'angular', 'nodejs', 'express', 'django', 'flask',
      'chatbot', 'bot', 'agente', 'agent', 'llm', 'ai', 'machine learning',
      'deep learning', 'neural', 'red neuronal', 'modelo', 'entrenamiento',
    ],
  },
  {
    id: 'ciencia-datos',
    label: 'Ciencia de datos',
    emoji: '📊',
    description: 'Analisis de datos, ML y estadistica',
    keywords: [
      'datos', 'data', 'dataset', 'csv', 'excel', 'pandas', 'numpy', 'scipy',
      'estadistica', 'statistics', 'analisis', 'analysis', 'analitica', 'analytics',
      'grafica', 'grafico', 'visualizacion', 'visualization', 'chart', 'plot',
      'machine learning', 'ml', 'deep learning', 'dl', 'red neuronal', 'neural',
      'modelo predictivo', 'prediccion', 'prediction', 'clasificacion', 'classification',
      'regresion', 'regression', 'clustering', 'cluster', 'segmentacion',
      'jupyter', 'notebook', 'colab', 'tensorflow', 'pytorch', 'keras', 'sklearn',
      'pipeline', 'etl', 'feature engineering', 'overfitting', 'cross-validation',
      'inferencia', 'inference', 'hipotesis', 'hypothesis', 'correlacion', 'correlation',
      'cientifico', 'scientist', 'investigar datos', 'mineria de datos', 'data mining',
    ],
  },
  {
    id: 'marketing',
    label: 'Marketing',
    emoji: '📣',
    description: 'Contenido, campanas y estrategia de marca',
    keywords: [
      'marketing', 'publicidad', 'advertising', 'ad', 'anuncio', 'campana', 'campaign',
      'contenido', 'content', 'copy', 'copywriting', 'texto publicitario',
      'redes sociales', 'social media', 'instagram', 'twitter', 'linkedin', 'tiktok',
      'facebook', 'youtube', 'email', 'newsletter', 'email marketing',
      'seo', 'posicionamiento', 'blog', 'post', 'articulo', 'article',
      'marca', 'brand', 'branding', 'identidad', 'logo', 'slogan', 'tagline',
      'cliente', 'customer', 'audiencia', 'audience', 'buyer persona',
      'funnel', 'embudo', 'conversion', 'cta', 'call to action',
      'producto', 'product', 'lanzamiento', 'launch', 'promocion', 'promotion',
      'influencer', 'colaboracion', 'partnership', 'afiliado', 'affiliate',
      'roi', 'kpi', 'metricas', 'metrics', 'engagement', 'alcance', 'reach',
      'vender', 'ventas', 'sales', 'persuadir', 'convencer',
    ],
  },
  {
    id: 'traduccion',
    label: 'Traduccion',
    emoji: '🌐',
    description: 'Traduccion e interpretacion de idiomas',
    keywords: [
      'traducir', 'traduccion', 'translate', 'translation', 'idioma', 'language',
      'ingles', 'english', 'espanol', 'spanish', 'frances', 'french', 'aleman',
      'german', 'italiano', 'italian', 'portugues', 'portuguese', 'chino', 'chinese',
      'japones', 'japanese', 'coreano', 'korean', 'ruso', 'russian', 'arabe', 'arabic',
      'subtitulos', 'subtitles', 'doblaje', 'dubbing', 'interpretacion', 'interpretation',
      'localizacion', 'localization', 'multilingual', 'multilingue',
      'texto en otro idioma', 'convertir idioma', 'cambiar idioma',
      'documento bilingue', 'glosario', 'terminologia', 'terminology',
    ],
  },
  {
    id: 'prompting',
    label: 'Prompting',
    emoji: '⚡',
    description: 'Diseno y optimizacion de prompts',
    keywords: [
      'prompt', 'prompting', 'instrucciones', 'instructions', 'indicaciones',
      'chain of thought', 'few-shot', 'zero-shot', 'one-shot', 'sistema',
      'system prompt', 'rol', 'role', 'contexto', 'context', 'temperatura',
      'token', 'tokens', 'optimizar prompt', 'mejorar prompt', 'disenar prompt',
      'ingenieria de prompts', 'prompt engineering', 'prompt design',
      'jailbreak', 'guardrail', 'filtro', 'restriccion', 'constraint',
      'output format', 'formato de salida', 'json', 'structured output',
      'razonamiento', 'reasoning', 'chain', 'cadena', 'paso a paso', 'step by step',
    ],
  },
  {
    id: 'imagenes',
    label: 'Imagenes',
    emoji: '🖼️',
    description: 'Generacion y edicion de imagenes con IA',
    keywords: [
      'imagen', 'image', 'foto', 'photo', 'fotografia', 'photography', 'ilustracion',
      'illustration', 'dibujar', 'draw', 'generar imagen', 'generate image',
      'arte digital', 'digital art', 'pixel art', 'concept art', 'diseño',
      'midjourney', 'dalle', 'stable diffusion', 'flux', 'firefly', 'adobe',
      'fotorrealista', 'photorealistic', 'render', '3d', 'animacion',
      'avatar', 'retrato', 'portrait', 'paisaje', 'landscape', 'fondo', 'background',
      'logo', 'icono', 'icon', 'banner', 'thumbnail', 'portada', 'cover',
      'poster', 'flyer', 'mockup', 'prototipo visual', 'wireframe',
      'inpainting', 'outpainting', 'upscale', 'mejorar imagen',
    ],
  },
  {
    id: 'estudio',
    label: 'Estudio',
    emoji: '📚',
    description: 'Aprendizaje, resumenes y educacion',
    keywords: [
      'estudiar', 'estudio', 'study', 'learning', 'aprender', 'aprendizaje',
      'examen', 'exam', 'test', 'quiz', 'flashcard', 'tarjeta', 'repaso', 'review',
      'resumen', 'summary', 'resumir', 'summarize', 'clase', 'course', 'curso',
      'universidad', 'university', 'colegio', 'school', 'escuela', 'secundaria',
      'tarea', 'homework', 'trabajo', 'assignment', 'investigacion', 'ensayo', 'essay',
      'matematica', 'fisica', 'quimica', 'biologia', 'historia', 'geografia',
      'literatura', 'filosofia', 'economia', 'derecho', 'medicina',
      'entender', 'understand', 'explicar', 'explain', 'concepto', 'concept',
      'guia', 'guide', 'tutorial', 'paso a paso', 'beginner', 'principiante',
      'nota', 'apuntes', 'notes', 'organizacion', 'planificar', 'schedule',
    ],
  },
  {
    id: 'finanzas',
    label: 'Finanzas',
    emoji: '💰',
    description: 'Analisis financiero, inversiones y contabilidad',
    keywords: [
      'finanzas', 'finance', 'financiero', 'financial', 'dinero', 'money',
      'inversion', 'investment', 'invertir', 'invest', 'bolsa', 'stock', 'accion',
      'cripto', 'crypto', 'bitcoin', 'ethereum', 'blockchain',
      'presupuesto', 'budget', 'gasto', 'expense', 'ingreso', 'income',
      'contabilidad', 'accounting', 'balance', 'cuenta', 'impuesto', 'tax',
      'banco', 'bank', 'credito', 'credit', 'deuda', 'debt', 'prestamo', 'loan',
      'roi', 'retorno', 'return', 'rendimiento', 'yield', 'dividendo', 'dividend',
      'mercado', 'market', 'economia', 'economy', 'pib', 'gdp', 'inflacion', 'inflation',
      'modelo financiero', 'financial model', 'proyeccion', 'forecast', 'valuacion',
      'valoracion', 'valuation', 'dcf', 'flujo de caja', 'cash flow',
      'riesgo', 'risk', 'portfolio', 'cartera', 'diversificacion', 'hedging',
    ],
  },
  {
    id: 'matematicas',
    label: 'Matematicas',
    emoji: '∑',
    description: 'Calculo, algebra, estadistica y matematica avanzada',
    keywords: [
      'matematica', 'math', 'matematicas', 'mathematics', 'calculo', 'calculus',
      'algebra', 'geometria', 'geometry', 'trigonometria', 'trigonometry',
      'estadistica', 'statistics', 'probabilidad', 'probability',
      'ecuacion', 'equation', 'formula', 'derivada', 'derivative', 'integral',
      'limite', 'limit', 'serie', 'series', 'vector', 'matriz', 'matrix',
      'numero', 'number', 'fraccion', 'fraction', 'porcentaje', 'percentage',
      'logaritmo', 'logarithm', 'exponencial', 'exponential',
      'optimizacion', 'optimization', 'maximizar', 'minimizar',
      'grafica', 'graph', 'funcion', 'function', 'dominio', 'domain', 'rango', 'range',
      'demostracion', 'proof', 'teorema', 'theorem', 'lema', 'lemma',
      'combinatoria', 'combinatorics', 'matematica discreta', 'discrete math',
      'resolver', 'solve', 'calcular', 'calculate', 'computar',
    ],
  },
  {
    id: 'arte',
    label: 'Arte y Creatividad',
    emoji: '🎨',
    description: 'Creacion artistica, diseno y expresion visual',
    keywords: [
      'arte', 'art', 'artista', 'artist', 'creativo', 'creative', 'creatividad',
      'diseno', 'design', 'disenador', 'designer', 'visual', 'estetica', 'aesthetic',
      'pintura', 'painting', 'dibujo', 'drawing', 'escultura', 'sculpture',
      'fotografia', 'photography', 'cine', 'cinema', 'pelicula', 'film',
      'animacion', 'animation', 'ilustracion', 'illustration',
      'concept art', 'character design', 'worldbuilding',
      'color', 'composicion', 'composition', 'perspectiva', 'perspective',
      'estilo', 'style', 'minimalismo', 'minimalism', 'surrealismo', 'surrealism',
      'portada', 'cover', 'album', 'galeria', 'gallery', 'exposicion',
      'narrativa visual', 'storyboard', 'comic', 'manga', 'novela grafica',
      'branding visual', 'identidad visual', 'ui', 'ux',
    ],
  },
  {
    id: 'video',
    label: 'Video',
    emoji: '🎬',
    description: 'Generacion y edicion de video con IA',
    keywords: [
      'video', 'pelicula', 'film', 'corto', 'short film', 'animacion', 'animation',
      'generar video', 'generate video', 'clip', 'cinematografico', 'cinematic',
      'sora', 'runway', 'kling', 'pika', 'videogeneration',
      'guion', 'script', 'storyboard', 'escena', 'scene', 'plano', 'shot',
      'edicion', 'edit', 'editar', 'montar', 'montaje', 'post-produccion',
      'efectos visuales', 'vfx', 'cgi', 'motion graphics', 'motion design',
      'youtube', 'reels', 'tiktok', 'shorts', 'contenido video',
      'documental', 'documentary', 'serie', 'episodio', 'trailer',
      'camara', 'camera', 'movimiento de camara', 'traveling', 'zoom',
    ],
  },
  {
    id: 'audio',
    label: 'Audio y Musica',
    emoji: '🎵',
    description: 'Generacion de musica, voz y audio',
    keywords: [
      'musica', 'music', 'cancion', 'song', 'melodia', 'melody', 'armonia', 'harmony',
      'generar musica', 'generate music', 'componer', 'compose', 'composicion',
      'suno', 'udio', 'elevenlabs', 'voz', 'voice', 'tts', 'text to speech',
      'podcast', 'audio', 'sonido', 'sound', 'grabacion', 'recording',
      'letra', 'lyrics', 'beat', 'ritmo', 'rhythm', 'instrumento', 'instrument',
      'banda sonora', 'soundtrack', 'bgm', 'jingle', 'efecto de sonido',
      'transcripcion', 'transcription', 'transcribir', 'subtitulo', 'subtitle',
      'doblaje', 'dubbing', 'narrador', 'narrator', 'narrar', 'leer en voz alta',
      'clonacion de voz', 'voice cloning', 'sintetizar voz',
    ],
  },
  {
    id: 'legal',
    label: 'Legal',
    emoji: '⚖️',
    description: 'Analisis de contratos y asesoria juridica',
    keywords: [
      'legal', 'juridico', 'ley', 'law', 'derecho', 'right', 'contrato', 'contract',
      'clausula', 'clause', 'terminos', 'terms', 'condiciones', 'conditions',
      'abogado', 'lawyer', 'attorney', 'notario', 'notary', 'fiscal', 'juez',
      'tribunal', 'court', 'juicio', 'trial', 'demanda', 'lawsuit', 'litigio',
      'propiedad intelectual', 'intellectual property', 'patente', 'patent',
      'marca registrada', 'trademark', 'copyright', 'derechos de autor',
      'privacidad', 'privacy', 'gdpr', 'rgpd', 'datos personales', 'personal data',
      'reglamento', 'regulation', 'cumplimiento', 'compliance', 'normativa',
      'acuerdo', 'agreement', 'nda', 'confidencialidad', 'confidentiality',
      'laboral', 'labor', 'empleo', 'employment', 'despido', 'termination',
    ],
  },
  {
    id: 'medicina',
    label: 'Medicina y Salud',
    emoji: '🏥',
    description: 'Informacion medica y analisis clinico',
    keywords: [
      'medico', 'medical', 'medicina', 'medicine', 'salud', 'health', 'clinico', 'clinical',
      'enfermedad', 'disease', 'diagnostico', 'diagnosis', 'sintoma', 'symptom',
      'tratamiento', 'treatment', 'farmaco', 'drug', 'medicamento', 'medication',
      'dosis', 'dose', 'efectos secundarios', 'side effects', 'interaccion',
      'laboratorio', 'lab', 'analisis', 'analisis de sangre', 'blood test',
      'radiografia', 'xray', 'mri', 'resonancia', 'ecografia', 'ultrasound',
      'cirugia', 'surgery', 'hospital', 'clinica', 'urgencias', 'emergency',
      'paciente', 'patient', 'doctor', 'enfermero', 'nurse', 'especialista',
      'nutricion', 'nutrition', 'dieta', 'diet', 'ejercicio', 'exercise',
      'salud mental', 'mental health', 'psicologia', 'psychology', 'terapia', 'therapy',
      'investigacion clinica', 'clinical trial', 'estudio', 'paper medico',
    ],
  },
  {
    id: 'productividad',
    label: 'Productividad',
    emoji: '⚙️',
    description: 'Automatizacion, organizacion y flujos de trabajo',
    keywords: [
      'productividad', 'productivity', 'automatizar', 'automate', 'automatizacion',
      'workflow', 'flujo de trabajo', 'proceso', 'process', 'eficiencia', 'efficiency',
      'organizacion', 'organization', 'planificar', 'plan', 'agenda', 'calendar',
      'tareas', 'tasks', 'todo', 'to-do', 'proyecto', 'project', 'management',
      'notion', 'zapier', 'make', 'integromat', 'n8n', 'integrar', 'integrate',
      'correo', 'email', 'gmail', 'outlook', 'comunicacion', 'communication',
      'reunion', 'meeting', 'zoom', 'teams', 'slack',
      'documento', 'document', 'presentacion', 'presentation', 'informe', 'report',
      'delegacion', 'delegation', 'prioridad', 'priority', 'urgente', 'importante',
      'notas', 'notes', 'segundo cerebro', 'second brain', 'pkm',
      'ahorro de tiempo', 'time saving', 'optimizar', 'optimize',
    ],
  },
  {
    id: 'roleplay',
    label: 'Roleplay',
    emoji: '🎭',
    description: 'Juegos de rol, personajes y narrativas interactivas',
    keywords: [
      'roleplay', 'rol', 'juego de rol', 'rpg', 'ttrpg', 'dnd', 'dungeons',
      'personaje', 'character', 'npc', 'protagonista', 'heroe', 'villain',
      'historia', 'story', 'narrativa', 'narrative', 'ficticio', 'fictional',
      'mundo', 'world', 'worldbuilding', 'universo', 'universe', 'lore',
      'aventura', 'adventure', 'quest', 'mision', 'mission', 'camapana', 'campaign',
      'dialogo', 'dialogue', 'conversacion', 'conversation', 'interactivo',
      'chat con personaje', 'simular', 'actuar', 'interpretar',
      'fantasy', 'fantasia', 'sci-fi', 'ciencia ficcion', 'horror', 'terror',
      'medieval', 'futurista', 'cyberpunk', 'steampunk', 'magia', 'magic',
      'juego', 'game', 'videojuego', 'video game', 'jugar', 'play',
    ],
  },
  {
    id: 'escritura',
    label: 'Escritura Creativa',
    emoji: '✍️',
    description: 'Ficcion, poesia, guiones y escritura literaria',
    keywords: [
      'escritura', 'writing', 'escribir', 'write', 'redactar', 'draft', 'borrador',
      'novela', 'novel', 'cuento', 'short story', 'relato', 'story', 'poema', 'poem',
      'poesia', 'poetry', 'guion', 'script', 'screenplay', 'obra de teatro', 'play',
      'ficcion', 'fiction', 'no ficcion', 'nonfiction', 'ensayo', 'essay',
      'blog', 'articulo', 'article', 'contenido', 'content', 'texto', 'text',
      'narrativa', 'narrative', 'trama', 'plot', 'estructura', 'structure',
      'personaje', 'character', 'desarrollo de personaje', 'arco narrativo',
      'estilo', 'style', 'voz', 'voice', 'tono', 'tone', 'genero', 'genre',
      'edicion', 'editing', 'corregir', 'mejorar texto', 'pulir',
      'autobiografia', 'autobiography', 'memoir', 'experiencia', 'diario', 'journal',
      'libro', 'book', 'capitulo', 'chapter', 'publicar', 'publish',
    ],
  },
  {
    id: 'investigacion',
    label: 'Investigacion',
    emoji: '🔬',
    description: 'Investigacion academica, cientifica y periodistica',
    keywords: [
      'investigar', 'investigate', 'investigacion', 'research', 'buscar', 'search',
      'fuente', 'source', 'referencia', 'reference', 'cita', 'citation', 'bibliografía',
      'paper', 'articulo cientifico', 'journal', 'publicacion', 'publication',
      'academico', 'academic', 'cientifico', 'scientific', 'universidad', 'tesis', 'thesis',
      'hipotesis', 'hypothesis', 'metodo', 'method', 'experimento', 'experiment',
      'datos', 'evidence', 'evidencia', 'hallazgo', 'finding', 'conclusion',
      'literatura', 'literature', 'revision', 'review', 'meta-analisis',
      'periodismo', 'journalism', 'periodista', 'journalist', 'noticia', 'news',
      'fact-checking', 'verificacion', 'veracidad', 'fuente confiable',
      'tendencia', 'trend', 'mercado', 'market', 'competidor', 'competitor',
      'informe', 'report', 'white paper', 'caso de estudio', 'case study',
    ],
  },
]

// Mapa de categoria por ID para acceso O(1)
export const CATEGORY_MAP = new Map<ModelCategory, Category>(
  CATEGORIES.map((c) => [c.id, c])
)
