export type Badge =
  | 'mejor-calidad'
  | 'mas-rapido'
  | 'gratuito'
  | 'open-source'
  | 'mas-barato'
  | 'multimodal'
  | 'razonamiento'
  | 'especializado'
  | 'privacidad'

export type ModelCategory =
  | 'coding'
  | 'ciencia-datos'
  | 'marketing'
  | 'traduccion'
  | 'prompting'
  | 'imagenes'
  | 'estudio'
  | 'finanzas'
  | 'matematicas'
  | 'arte'
  | 'video'
  | 'audio'
  | 'legal'
  | 'medicina'
  | 'productividad'
  | 'roleplay'
  | 'escritura'
  | 'investigacion'

export interface AIModel {
  id: string
  name: string
  company: string
  description: string
  categories: ModelCategory[]
  badges: Badge[]
  price: string
  reasonWhy: Record<ModelCategory, string>
  emoji: string
  tier: 'S' | 'A' | 'B'
}

// Mapa de acceso O(1) por categoria — vercel-react-best-practices: js-index-maps
export const MODELS_BY_CATEGORY = new Map<ModelCategory, AIModel[]>()

export const ALL_MODELS: AIModel[] = [
  // ─── CODING ────────────────────────────────────────────────────────────────
  {
    id: 'claude-sonnet',
    name: 'Claude Sonnet 4.5',
    company: 'Anthropic',
    description: 'Modelo de referencia para codigo. Razonamiento profundo, contexto de 200k tokens y excelente comprension de bases de codigo grandes.',
    categories: ['coding', 'prompting', 'escritura', 'investigacion', 'ciencia-datos'],
    badges: ['mejor-calidad', 'razonamiento'],
    price: '$3 / 1M tokens',
    emoji: '🤖',
    tier: 'S',
    reasonWhy: {
      coding: 'Comprende bases de codigo complejas, refactoriza con contexto amplio y genera tests precisos.',
      'ciencia-datos': 'Excelente para analizar datos, escribir pipelines y explicar resultados estadisticos.',
      marketing: 'Genera copy persuasivo y adapta el tono a distintas audiencias.',
      traduccion: 'Traduce con matices culturales y registros linguisticos correctos.',
      prompting: 'El modelo mas utilizado para disenar y optimizar prompts complejos.',
      imagenes: 'No genera imagenes directamente.',
      estudio: 'Explica conceptos con profundidad y crea resumenes estructurados.',
      finanzas: 'Analiza documentos financieros y modela escenarios de forma precisa.',
      matematicas: 'Resuelve problemas paso a paso con razonamiento formal.',
      arte: 'Genera descripciones creativas y ayuda a conceptualizar proyectos artisticos.',
      video: 'Puede ayudar a escribir guiones y storyboards detallados.',
      audio: 'Genera letras de canciones y scripts de podcasts de alta calidad.',
      legal: 'Analiza y redacta contratos con precision, aunque no reemplaza a un abogado.',
      medicina: 'Resume literatura medica y ayuda a interpretar estudios clinicos.',
      productividad: 'Automatiza tareas repetitivas y organiza informacion eficientemente.',
      roleplay: 'Crea personajes coherentes y narrativas inmersivas.',
      escritura: 'Domina todos los estilos narrativos con voz propia y coherencia.',
      investigacion: 'Sintetiza fuentes, identifica patrones y genera hipotesis solidas.',
    },
  },
  {
    id: 'claude-opus-46',
    name: 'Claude Opus 4.6',
    company: 'Anthropic',
    description: 'El modelo flagship de Anthropic. Maxima capacidad de razonamiento, analisis profundo y escritura avanzada. Para tareas que exigen juicio complejo y precision excepcional.',
    categories: ['escritura', 'investigacion', 'legal', 'medicina', 'prompting', 'coding'],
    badges: ['mejor-calidad', 'razonamiento', 'privacidad'],
    price: '$15 / 1M tokens',
    emoji: '🔮',
    tier: 'S',
    reasonWhy: {
      coding: 'Razonamiento de alto nivel para arquitectura de software, debugging complejo y revisiones de codigo criticas.',
      'ciencia-datos': 'Analiza hipotesis cientificas, interpreta resultados estadisticos complejos y disenha experimentos.',
      marketing: 'Genera estrategias de contenido con profundidad analitica y adaptacion de tono superior.',
      traduccion: 'Traduce con matices culturales profundos, registros formales y terminologia especializada.',
      prompting: 'El mejor modelo para disenar sistemas de prompts complejos, cadenas de razonamiento y agentes.',
      imagenes: 'No genera imagenes, pero describe y analiza contenido visual con detalle excepcional.',
      estudio: 'Explica conceptos dificiles con analogias precisas y genera material de estudio de nivel universitario.',
      finanzas: 'Analiza instrumentos financieros complejos, modela riesgos y redacta informes con rigor tecnico.',
      matematicas: 'Demuestra teoremas, resuelve problemas de matematica avanzada y verifica proofs paso a paso.',
      arte: 'Critica y conceptualiza proyectos artisticos con vocabulario tecnico y referencias historicas precisas.',
      video: 'Escribe guiones cinematograficos, analiza narrativa audiovisual y genera briefs de produccion detallados.',
      audio: 'Compone letras con estructura poetica avanzada y genera libretos para podcasts de alta calidad.',
      legal: 'Redacta y analiza contratos complejos, identifica clausulas de riesgo y argumenta posiciones juridicas.',
      medicina: 'Sintetiza literatura clinica avanzada, interpreta resultados de laboratorio y resume casos complejos.',
      productividad: 'Disenha sistemas de trabajo, automatiza decisiones complejas y estructura proyectos de gran escala.',
      roleplay: 'Crea personajes con profundidad psicologica, worldbuilding coherente y narrativas inmersivas de largo aliento.',
      escritura: 'La maxima expresion en escritura creativa: voz propia, estructura narrativa solida y estilo refinado.',
      investigacion: 'Sintetiza multiples fuentes, identifica contradicciones en la literatura y formula hipotesis originales.',
    },
  },
  {
    id: 'gpt-41',
    name: 'GPT-4.1',
    company: 'OpenAI',
    description: 'El modelo mas capaz de OpenAI para tareas de codigo y razonamiento multimodal. Acepta imagenes, audio y documentos.',
    categories: ['coding', 'ciencia-datos', 'finanzas', 'investigacion', 'productividad'],
    badges: ['mejor-calidad', 'multimodal'],
    price: '$2 / 1M tokens',
    emoji: '🧠',
    tier: 'S',
    reasonWhy: {
      coding: 'Genera codigo limpio, detecta bugs sutiles y explica soluciones paso a paso.',
      'ciencia-datos': 'Integra vision para analizar graficos y tablas directamente desde imagenes.',
      marketing: 'Crea estrategias de contenido multicanal con datos de contexto.',
      traduccion: 'Traduce texto e imagenes simultaneamente con comprension contextual.',
      prompting: 'Sigue instrucciones complejas con alta fidelidad y consistencia.',
      imagenes: 'Puede analizar y describir imagenes con detalle excepcional.',
      estudio: 'Genera flashcards, resumenes y examenes de practica automaticamente.',
      finanzas: 'Procesa reportes financieros (PDF, imagenes) y extrae metricas clave.',
      matematicas: 'Resuelve ecuaciones, optimizaciones y problemas de calculo avanzado.',
      arte: 'Analiza obras de arte y ayuda a conceptualizar proyectos visuales.',
      video: 'Escribe guiones y analiza frames de video con descripcion detallada.',
      audio: 'Transcribe y analiza audio con alta precision.',
      legal: 'Extrae clausulas clave de contratos en formato PDF o imagen.',
      medicina: 'Interpreta imagenes medicas (radiografias) con contexto clinico.',
      productividad: 'Integra con APIs de Office y automatiza flujos de trabajo complejos.',
      roleplay: 'Mantiene personajes consistentes en conversaciones largas.',
      escritura: 'Genera narrativas largas con coherencia y estilo propio.',
      investigacion: 'Analiza papers cientificos en PDF y sintetiza hallazgos.',
    },
  },
  {
    id: 'gemini-25-pro',
    name: 'Gemini 2.5 Pro',
    company: 'Google',
    description: 'Modelo insignia de Google con ventana de contexto de 1M tokens. Ideal para proyectos grandes y analisis multimodal de largo aliento.',
    categories: ['coding', 'investigacion', 'ciencia-datos', 'estudio', 'matematicas'],
    badges: ['mejor-calidad', 'multimodal', 'razonamiento'],
    price: '$3.50 / 1M tokens',
    emoji: '💎',
    tier: 'S',
    reasonWhy: {
      coding: 'Contexto de 1M tokens permite analizar proyectos enteros de una sola vez.',
      'ciencia-datos': 'Procesa datasets completos y genera visualizaciones con Google Colab.',
      marketing: 'Analiza campanas completas y genera estrategias basadas en datos.',
      traduccion: 'Contexto largo permite traducir libros o documentos extensos completos.',
      prompting: 'Excelente para multi-turn prompting y seguimiento de instrucciones largas.',
      imagenes: 'Analiza y compara multiples imagenes en una sola consulta.',
      estudio: 'Puede leer libros completos y generar guias de estudio comprehensivas.',
      finanzas: 'Procesa reportes anuales completos y modelos financieros extensos.',
      matematicas: 'Capacidad avanzada de razonamiento para matematicas universitarias.',
      arte: 'Analiza portfolios completos y sugiere direcciones artisticas.',
      video: 'Puede analizar videos completos frame por frame.',
      audio: 'Transcripcion y analisis de audio de alta calidad.',
      legal: 'Lee contratos legales completos de cientos de paginas sin perdida de contexto.',
      medicina: 'Analiza historiales medicos completos y literatura clinica extensa.',
      productividad: 'Integra con Google Workspace para automatizar flujos completos.',
      roleplay: 'Mantiene worldbuilding coherente en narrativas muy extensas.',
      escritura: 'Escribe novelas completas con consistencia de personajes y trama.',
      investigacion: 'Lee y sintetiza decenas de papers cientificos en una sola sesion.',
    },
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    company: 'DeepSeek',
    description: 'El modelo open-source mas potente para codigo. Rendimiento comparable a GPT-4 a una fraccion del costo.',
    categories: ['coding', 'matematicas', 'ciencia-datos'],
    badges: ['open-source', 'mas-barato', 'razonamiento'],
    price: '$0.27 / 1M tokens',
    emoji: '🔷',
    tier: 'A',
    reasonWhy: {
      coding: 'Especializado en codigo con entrenamiento masivo en repositorios de GitHub.',
      'ciencia-datos': 'Excelente para Python cientifico, pandas, numpy y machine learning.',
      marketing: 'Funcional para tareas de marketing con muy buen precio.',
      traduccion: 'Buena calidad en traduccion, especialmente para idiomas asiaticos.',
      prompting: 'Sigue instrucciones tecnicas con precision y consistencia.',
      imagenes: 'No genera imagenes.',
      estudio: 'Explica conceptos tecnicos de forma clara y estructurada.',
      finanzas: 'Capaz de modelado financiero y analisis cuantitativo.',
      matematicas: 'Modelo de razonamiento matematico de clase mundial.',
      arte: 'Limitado para tareas puramente artisticas.',
      video: 'No especializado en video.',
      audio: 'No especializado en audio.',
      legal: 'Puede analizar textos legales aunque no es su fuerte.',
      medicina: 'Util para analisis de datos medicos y literatura cientifica.',
      productividad: 'Automatiza tareas de programacion y scripts de forma economica.',
      roleplay: 'Funcional pero no su especialidad principal.',
      escritura: 'Buena calidad de escritura tecnica y documentacion.',
      investigacion: 'Excelente para investigacion tecnica y cientifica.',
    },
  },
  // ─── IMAGENES ──────────────────────────────────────────────────────────────
  {
    id: 'midjourney-v7',
    name: 'Midjourney v7',
    company: 'Midjourney',
    description: 'El estandar de oro en generacion de imagenes artisticas. Calidad visual insuperable para arte conceptual, ilustraciones y fotorrealismo.',
    categories: ['imagenes', 'arte'],
    badges: ['mejor-calidad', 'especializado'],
    price: '$10 / mes (Basic)',
    emoji: '🎨',
    tier: 'S',
    reasonWhy: {
      coding: 'No aplica para codigo.',
      'ciencia-datos': 'No aplica para ciencia de datos.',
      marketing: 'Genera assets visuales para campanas con calidad profesional.',
      traduccion: 'No aplica para traduccion.',
      prompting: 'Requiere prompts especificos — ideal para aprender prompt de imagenes.',
      imagenes: 'La mejor calidad artistica disponible. Inigualable para arte conceptual.',
      estudio: 'Genera diagramas e ilustraciones educativas visualmente atractivas.',
      finanzas: 'No aplica directamente.',
      matematicas: 'No aplica.',
      arte: 'Referencia absoluta para artistas digitales y directores de arte.',
      video: 'Genera frames de video y storyboards con calidad cinematografica.',
      audio: 'No aplica.',
      legal: 'No aplica.',
      medicina: 'Genera ilustraciones medicas y anatomicas para materiales educativos.',
      productividad: 'Acelera la creacion de assets visuales para diseno.',
      roleplay: 'Genera retratos de personajes y escenas de worldbuilding.',
      escritura: 'Crea portadas e ilustraciones para libros y publicaciones.',
      investigacion: 'Genera visualizaciones para presentaciones de investigacion.',
    },
  },
  {
    id: 'dalle3',
    name: 'DALL-E 3',
    company: 'OpenAI',
    description: 'Generacion de imagenes fotorrealistas con excelente comprension de texto. Integrado en ChatGPT para flujo conversacional.',
    categories: ['imagenes', 'arte', 'marketing'],
    badges: ['multimodal', 'especializado'],
    price: 'Incluido en ChatGPT Plus ($20/mes)',
    emoji: '🖼️',
    tier: 'A',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'Genera graficos e infografias a partir de descripciones.',
      marketing: 'Crea imagenes para ads, redes sociales y materiales de marca rapidamente.',
      traduccion: 'No aplica.',
      prompting: 'Muy bueno siguiendo instrucciones textuales detalladas.',
      imagenes: 'Excelente comprension de prompts complejos y fotorrealismo.',
      estudio: 'Genera diagramas e ilustraciones educativas.',
      finanzas: 'Genera infografias de datos financieros.',
      matematicas: 'No aplica.',
      arte: 'Gran variedad de estilos artisticos con alta consistencia.',
      video: 'No genera video.',
      audio: 'No aplica.',
      legal: 'No aplica.',
      medicina: 'Ilustraciones medicas y material educativo.',
      productividad: 'Genera mockups y wireframes rapidamente.',
      roleplay: 'Genera imagenes de personajes y escenarios para TTRPG.',
      escritura: 'Portadas e ilustraciones para contenido escrito.',
      investigacion: 'Visualizaciones para presentaciones academicas.',
    },
  },
  {
    id: 'stable-diffusion-xl',
    name: 'Stable Diffusion XL',
    company: 'Stability AI',
    description: 'El modelo open-source mas popular para generacion de imagenes. Ejecutable localmente sin costo por imagen y altamente personalizable.',
    categories: ['imagenes', 'arte'],
    badges: ['open-source', 'gratuito', 'especializado'],
    price: 'Gratis (local) / $0.002/imagen (API)',
    emoji: '🌊',
    tier: 'A',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'Util para data augmentation en datasets de imagenes.',
      marketing: 'Genera assets visuales sin costo por imagen ejecutando localmente.',
      traduccion: 'No aplica.',
      prompting: 'Gran ecosistema de LoRAs y modelos fine-tuneados.',
      imagenes: 'Completamente personalizable con fine-tuning y LoRAs especificos.',
      estudio: 'Genera ilustraciones educativas sin limite de uso.',
      finanzas: 'No aplica directamente.',
      matematicas: 'No aplica.',
      arte: 'Ideal para artistas que quieren control total sobre el modelo.',
      video: 'Extensiones para animacion cuadro a cuadro.',
      audio: 'No aplica.',
      legal: 'No aplica.',
      medicina: 'Fine-tuning para imagenes medicas especializadas.',
      productividad: 'Sin costos variables — ideal para flujos de trabajo de alto volumen.',
      roleplay: 'Genera assets visuales ilimitados para campanas de rol.',
      escritura: 'Ilustraciones ilimitadas para proyectos editoriales.',
      investigacion: 'Util para investigacion en vision computacional.',
    },
  },
  {
    id: 'flux-pro',
    name: 'FLUX.1 Pro',
    company: 'Black Forest Labs',
    description: 'El modelo mas reciente que supera a DALL-E 3 en fotorrealismo y adherencia al prompt. El nuevo estandar para generacion profesional.',
    categories: ['imagenes', 'arte', 'marketing'],
    badges: ['mejor-calidad', 'especializado'],
    price: '$0.055 / imagen',
    emoji: '⚡',
    tier: 'S',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'No aplica directamente.',
      marketing: 'Calidad fotografica para ads y contenido comercial de alta gama.',
      traduccion: 'No aplica.',
      prompting: 'Adherencia al prompt superior a cualquier competidor actual.',
      imagenes: 'El modelo mas preciso siguiendo instrucciones textuales detalladas.',
      estudio: 'Genera ilustraciones educativas fotorrealistas.',
      finanzas: 'No aplica.',
      matematicas: 'No aplica.',
      arte: 'Perfecto para arte comercial y fotografia conceptual.',
      video: 'No genera video directamente.',
      audio: 'No aplica.',
      legal: 'No aplica.',
      medicina: 'Ilustraciones medicas fotorrealistas.',
      productividad: 'Prototipado visual rapido con alta calidad.',
      roleplay: 'Retratos de personajes con nivel de detalle fotografico.',
      escritura: 'Portadas de libros e ilustraciones de calidad editorial.',
      investigacion: 'Visualizaciones cientificas de alta calidad.',
    },
  },
  // ─── TRADUCCION ────────────────────────────────────────────────────────────
  {
    id: 'deepl',
    name: 'DeepL',
    company: 'DeepL SE',
    description: 'El modelo de traduccion especializado mas preciso del mercado. Captura matices, modismos y registro linguistico mejor que cualquier LLM general.',
    categories: ['traduccion'],
    badges: ['mejor-calidad', 'especializado'],
    price: 'Gratis (500k chars) / $8.99/mes Pro',
    emoji: '🌐',
    tier: 'S',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'Traduce documentacion tecnica con terminologia correcta.',
      marketing: 'Traduce copy publicitario preservando el impacto emocional.',
      traduccion: 'Referencia absoluta en calidad de traduccion. Maneja 33 idiomas con naturalidad.',
      prompting: 'Util para traducir prompts a otros idiomas.',
      imagenes: 'No aplica.',
      estudio: 'Traduce textos academicos y libros con precision academica.',
      finanzas: 'Traduce reportes financieros con terminologia tecnica correcta.',
      matematicas: 'No aplica.',
      arte: 'No aplica.',
      video: 'Genera subtitulos y traduce guiones.',
      audio: 'Traduce transcripciones con alta precision.',
      legal: 'Traduce documentos legales respetando la terminologia juridica.',
      medicina: 'Traduce literatura medica con vocabulario clinico correcto.',
      productividad: 'API para automatizar flujos de traduccion.',
      roleplay: 'No aplica.',
      escritura: 'Traduce libros y contenido literario con calidad editorial.',
      investigacion: 'Traduce papers cientificos manteniendo el rigor terminologico.',
    },
  },
  // ─── MATEMATICAS ───────────────────────────────────────────────────────────
  {
    id: 'wolfram-alpha',
    name: 'Wolfram Alpha',
    company: 'Wolfram Research',
    description: 'El motor computacional mas poderoso para matematicas, ciencias y datos cuantitativos. Calculo simbolico y numerico exacto.',
    categories: ['matematicas', 'ciencia-datos', 'finanzas'],
    badges: ['especializado', 'mejor-calidad'],
    price: 'Gratis / $7.25/mes Pro',
    emoji: '∑',
    tier: 'S',
    reasonWhy: {
      coding: 'Resuelve algoritmos matematicos y verifica implementaciones numericas.',
      'ciencia-datos': 'Analisis estadistico exacto y visualizacion de datos matematicos.',
      marketing: 'Analiza metricas y calcula ROI con precision exacta.',
      traduccion: 'No aplica.',
      prompting: 'No aplica.',
      imagenes: 'Genera graficas y visualizaciones matematicas.',
      estudio: 'Resuelve problemas paso a paso mostrando el proceso completo.',
      finanzas: 'Calculo de interes compuesto, amortizaciones y modelos cuantitativos.',
      matematicas: 'La referencia absoluta para calculo, algebra, estadistica y matematica discreta.',
      arte: 'Genera arte matematico (fractales, geometria).',
      video: 'No aplica.',
      audio: 'No aplica.',
      legal: 'No aplica.',
      medicina: 'Calculo de dosis, estadistica clinica y analisis de laboratorio.',
      productividad: 'Automatiza calculos repetitivos con la API.',
      roleplay: 'No aplica.',
      escritura: 'No aplica.',
      investigacion: 'Resuelve ecuaciones diferenciales y modelos matematicos complejos.',
    },
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    company: 'DeepSeek',
    description: 'Modelo de razonamiento matematico open-source que iguala a OpenAI o1. Pensamiento paso a paso para problemas complejos.',
    categories: ['matematicas', 'coding', 'ciencia-datos', 'investigacion'],
    badges: ['open-source', 'razonamiento', 'mas-barato'],
    price: '$0.55 / 1M tokens',
    emoji: '🔬',
    tier: 'S',
    reasonWhy: {
      coding: 'Razonamiento profundo para depuracion de algoritmos complejos.',
      'ciencia-datos': 'Excelente para derivar formulas estadisticas y modelos ML.',
      marketing: 'No su especialidad principal.',
      traduccion: 'No especializado.',
      prompting: 'Razona sobre la estructura de los prompts antes de responder.',
      imagenes: 'No genera imagenes.',
      estudio: 'Explica cada paso del razonamiento para maximo aprendizaje.',
      finanzas: 'Modelos cuantitativos y derivados financieros complejos.',
      matematicas: 'Iguala a OpenAI o1 en benchmarks matematicos olympiade-level.',
      arte: 'No aplica.',
      video: 'No aplica.',
      audio: 'No aplica.',
      legal: 'Razonamiento juridico y analisis de precedentes legales.',
      medicina: 'Razonamiento clinico y diagnostico diferencial.',
      productividad: 'No su fuerte principal.',
      roleplay: 'No especializado.',
      escritura: 'Escritura tecnica y academica rigurosa.',
      investigacion: 'Ideal para investigacion cientifica que requiere razonamiento formal.',
    },
  },
  // ─── AUDIO ─────────────────────────────────────────────────────────────────
  {
    id: 'suno-v4',
    name: 'Suno v4',
    company: 'Suno',
    description: 'Genera canciones completas con voz, instrumentos y produccion a partir de un prompt de texto. El estandar en generacion de musica con IA.',
    categories: ['audio', 'arte'],
    badges: ['mejor-calidad', 'especializado'],
    price: 'Gratis (10 canciones/dia) / $8/mes Pro',
    emoji: '🎵',
    tier: 'S',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'No aplica.',
      marketing: 'Genera jingles y musica para ads rapidamente sin costo de produccion.',
      traduccion: 'No aplica.',
      prompting: 'Aprende a escribir prompts musicales descriptivos.',
      imagenes: 'No aplica.',
      estudio: 'Crea canciones mnemonicas para memorizar contenido.',
      finanzas: 'No aplica.',
      matematicas: 'No aplica.',
      arte: 'Composicion musical completa desde cero en segundos.',
      video: 'Genera bandas sonoras originales para videos.',
      audio: 'La mejor herramienta para generar musica original completa con IA.',
      legal: 'No aplica.',
      medicina: 'No aplica.',
      productividad: 'Genera musica de fondo para sesiones de trabajo.',
      roleplay: 'Crea temas musicales para personajes y mundos ficticios.',
      escritura: 'Genera bandas sonoras para audiolibros y podcasts.',
      investigacion: 'No aplica.',
    },
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    company: 'ElevenLabs',
    description: 'Text-to-speech y clonacion de voz de la mas alta calidad. Narrador, doblaje y voces sinteticas hiperrealistas.',
    categories: ['audio', 'productividad', 'marketing'],
    badges: ['mejor-calidad', 'especializado'],
    price: 'Gratis (10k chars/mes) / $5/mes Starter',
    emoji: '🔊',
    tier: 'S',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'No aplica.',
      marketing: 'Genera voiceovers profesionales para ads y contenido audiovisual.',
      traduccion: 'Dobla audio a multiples idiomas manteniendo la voz original.',
      prompting: 'No aplica.',
      imagenes: 'No aplica.',
      estudio: 'Convierte apuntes y textos en audiolibros para estudiar mientras te mueves.',
      finanzas: 'No aplica.',
      matematicas: 'No aplica.',
      arte: 'Crea personajes de audio con voces unicas y expresivas.',
      video: 'Narración y doblaje profesional para videos y documentales.',
      audio: 'La referencia en text-to-speech de calidad humana y clonacion de voz.',
      legal: 'No aplica.',
      medicina: 'Convierte notas medicas en audio para profesionales en movimiento.',
      productividad: 'Convierte documentos a audio para consumo sin pantalla.',
      roleplay: 'Voces unicas y expresivas para personajes de rol.',
      escritura: 'Narración de audiolibros con calidad de estudio de grabacion.',
      investigacion: 'Convierte papers a audio para estudiar en desplazamientos.',
    },
  },
  // ─── VIDEO ─────────────────────────────────────────────────────────────────
  {
    id: 'runway-gen3',
    name: 'Runway Gen-3 Alpha',
    company: 'Runway',
    description: 'Generacion de video de alta calidad a partir de texto o imagen. El estandar profesional para produccion de video con IA.',
    categories: ['video', 'arte', 'marketing'],
    badges: ['mejor-calidad', 'especializado'],
    price: '$15/mes Standard',
    emoji: '🎬',
    tier: 'S',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'Genera visualizaciones animadas de datos.',
      marketing: 'Produce videos publicitarios de alta calidad rapidamente.',
      traduccion: 'No aplica.',
      prompting: 'Aprende a escribir prompts cinematograficos.',
      imagenes: 'Anima imagenes estaticas con calidad cinematografica.',
      estudio: 'Crea videos educativos animados.',
      finanzas: 'No aplica directamente.',
      matematicas: 'No aplica.',
      arte: 'Produccion de cortometrajes y video arte.',
      video: 'El estandar de la industria para generacion de video con IA de calidad profesional.',
      audio: 'No genera audio.',
      legal: 'No aplica.',
      medicina: 'Animaciones medicas para educacion y presentaciones.',
      productividad: 'Acelera la produccion de contenido de video.',
      roleplay: 'Genera cutscenes y trailers para campanas de rol.',
      escritura: 'Adapta guiones a teasers de video.',
      investigacion: 'Visualizaciones animadas para presentaciones cientificas.',
    },
  },
  {
    id: 'kling-ai',
    name: 'Kling AI',
    company: 'Kuaishou',
    description: 'Generacion de video de hasta 3 minutos con movimientos de camara profesionales. La alternativa mas asequible a Sora.',
    categories: ['video', 'arte'],
    badges: ['mas-barato', 'especializado'],
    price: 'Gratis (66 creditos/dia)',
    emoji: '🎥',
    tier: 'A',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'No aplica.',
      marketing: 'Genera videos de producto y testimoniales sinteticos.',
      traduccion: 'No aplica.',
      prompting: 'No aplica.',
      imagenes: 'No aplica.',
      estudio: 'Videos explicativos animados para conceptos complejos.',
      finanzas: 'No aplica.',
      matematicas: 'No aplica.',
      arte: 'Cortometrajes y video arte con plan gratuito generoso.',
      video: 'Videos de hasta 3 minutos con narrativa coherente y movimientos de camara.',
      audio: 'No genera audio.',
      legal: 'No aplica.',
      medicina: 'No aplica.',
      productividad: 'Produccion de video sin costo inicial.',
      roleplay: 'No aplica.',
      escritura: 'No aplica.',
      investigacion: 'No aplica.',
    },
  },
  // ─── INVESTIGACION ─────────────────────────────────────────────────────────
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    company: 'Perplexity',
    description: 'Motor de busqueda de IA con fuentes citadas en tiempo real. Combina busqueda web con razonamiento para respuestas verificables.',
    categories: ['investigacion', 'estudio', 'finanzas', 'medicina', 'legal'],
    badges: ['especializado', 'gratuito'],
    price: 'Gratis / $20/mes Pro',
    emoji: '🔍',
    tier: 'S',
    reasonWhy: {
      coding: 'Busca documentacion y ejemplos de codigo con fuentes actualizadas.',
      'ciencia-datos': 'Investiga papers y datasets con fuentes citadas.',
      marketing: 'Investiga tendencias de mercado y competidores en tiempo real.',
      traduccion: 'No especializado.',
      prompting: 'Investiga mejores practicas de prompting con ejemplos reales.',
      imagenes: 'No genera imagenes.',
      estudio: 'Fuentes verificadas para investigacion academica.',
      finanzas: 'Datos financieros actualizados con fuentes de confianza.',
      matematicas: 'Busca soluciones y teoremas matematicos con referencias.',
      arte: 'Investiga artistas, movimientos y tecnicas con fuentes.',
      video: 'No genera video.',
      audio: 'No genera audio.',
      legal: 'Jurisprudencia y normativas actualizadas con fuentes verificables.',
      medicina: 'Literatura medica actualizada con referencias a PubMed.',
      productividad: 'Investiga y sintetiza informacion rapido.',
      roleplay: 'No aplica.',
      escritura: 'Investigacion factual para escritura no-ficcion.',
      investigacion: 'La herramienta definitiva para investigacion verificable en tiempo real.',
    },
  },
  // ─── PRODUCTIVIDAD ─────────────────────────────────────────────────────────
  {
    id: 'notebooklm',
    name: 'NotebookLM',
    company: 'Google',
    description: 'Analiza tus propios documentos, genera resumenes, podcasts de audio y responde preguntas basadas en tus fuentes.',
    categories: ['estudio', 'investigacion', 'productividad', 'medicina', 'legal'],
    badges: ['gratuito', 'especializado'],
    price: 'Gratis',
    emoji: '📓',
    tier: 'A',
    reasonWhy: {
      coding: 'Analiza documentacion tecnica de tus proyectos.',
      'ciencia-datos': 'Procesa y sintetiza papers de ciencia de datos de tu biblioteca.',
      marketing: 'Analiza investigacion de mercado y genera insights.',
      traduccion: 'No especializado.',
      prompting: 'Aprende de documentacion de prompting que tu subas.',
      imagenes: 'No genera imagenes.',
      estudio: 'Convierte tus apuntes en podcasts, resumenes y quizzes automaticamente.',
      finanzas: 'Analiza reportes anuales y documentos financieros propios.',
      matematicas: 'No especializado.',
      arte: 'Analiza libros y recursos artisticos que subas.',
      video: 'No genera video.',
      audio: 'Genera podcasts de audio desde tus documentos.',
      legal: 'Analiza contratos y documentos legales propios con Q&A.',
      medicina: 'Analiza tu literatura medica personal con Q&A preciso.',
      productividad: 'Tu segundo cerebro — organiza y accede a toda tu informacion.',
      roleplay: 'No aplica.',
      escritura: 'Analiza tu propia investigacion para proyectos de escritura.',
      investigacion: 'Organiza y conversa con toda tu biblioteca de papers.',
    },
  },
  {
    id: 'gemini-flash',
    name: 'Gemini 2.5 Flash',
    company: 'Google',
    description: 'El modelo mas rapido y economico de Google. Ideal para tareas de alto volumen que necesitan respuestas instantaneas.',
    categories: ['productividad', 'traduccion', 'estudio', 'marketing'],
    badges: ['mas-rapido', 'mas-barato', 'gratuito'],
    price: 'Gratis / $0.075 / 1M tokens',
    emoji: '⚡',
    tier: 'A',
    reasonWhy: {
      coding: 'Rapido para tareas simples de codigo y completacion.',
      'ciencia-datos': 'Procesamiento rapido de datos con latencia minima.',
      marketing: 'Generacion rapida de copies y variaciones A/B.',
      traduccion: 'Traduccion rapida y economica para alto volumen.',
      prompting: 'Iteracion rapida en desarrollo de prompts.',
      imagenes: 'No genera imagenes.',
      estudio: 'Respuestas rapidas a preguntas de estudio.',
      finanzas: 'No su especialidad.',
      matematicas: 'Calculo rapido para problemas de dificultad moderada.',
      arte: 'No aplica.',
      video: 'No genera video.',
      audio: 'No genera audio.',
      legal: 'No aplica.',
      medicina: 'No aplica.',
      productividad: 'El mas economico para automatizar flujos de trabajo de alto volumen.',
      roleplay: 'Respuestas rapidas en rol conversacional.',
      escritura: 'Generacion rapida de borradores y variaciones.',
      investigacion: 'Busquedas rapidas y resumenes de documentos.',
    },
  },
  // ─── MARKETING ─────────────────────────────────────────────────────────────
  {
    id: 'jasper-ai',
    name: 'Jasper AI',
    company: 'Jasper',
    description: 'Plataforma de IA especializada en marketing y contenido de marca. Incluye plantillas para ads, emails, blogs y redes sociales.',
    categories: ['marketing', 'escritura', 'productividad'],
    badges: ['especializado'],
    price: '$39/mes Creator',
    emoji: '📣',
    tier: 'A',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'No aplica.',
      marketing: 'Especializado en copy de marketing con plantillas para cada formato y canal.',
      traduccion: 'No aplica.',
      prompting: 'Plantillas de prompts optimizadas para cada tipo de contenido.',
      imagenes: 'Incluye generacion de imagenes para contenido.',
      estudio: 'No aplica.',
      finanzas: 'No aplica.',
      matematicas: 'No aplica.',
      arte: 'No aplica.',
      video: 'No aplica.',
      audio: 'No aplica.',
      legal: 'No aplica.',
      medicina: 'No aplica.',
      productividad: 'Flujos de trabajo de contenido completos con integraciones.',
      roleplay: 'No aplica.',
      escritura: 'Blog posts, newsletters y contenido SEO-optimizado.',
      investigacion: 'Investigacion competitiva y analisis de mercado.',
    },
  },
  // ─── LEGAL ─────────────────────────────────────────────────────────────────
  {
    id: 'claude-opus',
    name: 'Claude Opus 4.6',
    company: 'Anthropic',
    description: 'El modelo mas potente de Anthropic. Razonamiento de nivel experto para tareas que requieren maxima precision y profundidad analitica.',
    categories: ['legal', 'finanzas', 'medicina', 'investigacion', 'matematicas'],
    badges: ['mejor-calidad', 'razonamiento'],
    price: '$15 / 1M tokens',
    emoji: '🏛️',
    tier: 'S',
    reasonWhy: {
      coding: 'Arquitectura de sistemas y revision de codigo de alta complejidad.',
      'ciencia-datos': 'Analisis estadistico avanzado e interpretacion de modelos.',
      marketing: 'Estrategia de marketing de alto nivel y analisis de audiencias.',
      traduccion: 'Traduccion con profundidad cultural y matices filosoficos.',
      prompting: 'Diseno de sistemas de prompts complejos y cadenas de razonamiento.',
      imagenes: 'No genera imagenes.',
      estudio: 'Tutoria universitaria en materias complejas como fisica o filosofia.',
      finanzas: 'Analisis financiero de nivel institucional y modelado de riesgos.',
      matematicas: 'Demostraciones matematicas formales y teoremas complejos.',
      arte: 'Critica y teoria del arte con profundidad analitica excepcional.',
      video: 'Escritura de guiones largos con estructura narrativa compleja.',
      audio: 'No genera audio.',
      legal: 'Analisis juridico exhaustivo con precedentes y razonamiento formal.',
      medicina: 'Razonamiento clinico diferencial y revision de literatura medica.',
      productividad: 'Automatizacion de tareas de alto nivel cognitivo.',
      roleplay: 'Narrativas complejas con personajes profundamente desarrollados.',
      escritura: 'Literatura de alta calidad y ensayos academicos rigurosos.',
      investigacion: 'El mejor para investigacion cientifica y academica profunda.',
    },
  },
  // ─── FINANZAS ──────────────────────────────────────────────────────────────
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    company: 'OpenAI',
    description: 'Modelo multimodal de OpenAI con velocidad y precio optimizados. El mas versatil para uso diario en texto, imagenes y voz.',
    categories: ['finanzas', 'productividad', 'escritura', 'estudio', 'marketing', 'roleplay'],
    badges: ['multimodal', 'mas-rapido'],
    price: '$2.50 / 1M tokens',
    emoji: '🌀',
    tier: 'A',
    reasonWhy: {
      coding: 'Solido para la mayoria de tareas de codigo con velocidad de respuesta alta.',
      'ciencia-datos': 'Analiza datos en tiempo real con interpretacion de graficas.',
      marketing: 'Genera contenido multimodal — texto e imagenes coordinados.',
      traduccion: 'Traduccion rapida con comprension contextual solida.',
      prompting: 'Excelente en seguir instrucciones complejas con consistencia.',
      imagenes: 'Analisis de imagenes de alta precision.',
      estudio: 'Explica conceptos con ejemplos visuales cuando se proporcionan imagenes.',
      finanzas: 'Analiza graficos financieros e interpreta datos de mercado.',
      matematicas: 'Resuelve problemas con soporte de codigo Python en tiempo real.',
      arte: 'Analiza composicion artistica y teoria del color.',
      video: 'Analisis de contenido de video frame por frame.',
      audio: 'Transcripcion y analisis de audio en tiempo real.',
      legal: 'Analisis de contratos con vision para PDFs escaneados.',
      medicina: 'Interpretacion de imagenes medicas con contexto clinico.',
      productividad: 'El asistente diario mas completo — texto, voz e imagenes.',
      roleplay: 'Conversaciones naturales con memoria de contexto larga.',
      escritura: 'Edicion y mejora de textos con retroalimentacion detallada.',
      investigacion: 'Combina busqueda web con analisis propio en tiempo real.',
    },
  },
  // ─── MEDICINA ──────────────────────────────────────────────────────────────
  {
    id: 'medpalm2',
    name: 'Med-PaLM 2',
    company: 'Google',
    description: 'Modelo especializado en medicina clinica. Primer modelo en alcanzar nivel experto en preguntas del examen USMLE. Solo para profesionales.',
    categories: ['medicina'],
    badges: ['especializado', 'mejor-calidad'],
    price: 'Enterprise (Google Cloud)',
    emoji: '🏥',
    tier: 'S',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'Analisis de datos clinicos y epidemiologia.',
      marketing: 'No aplica.',
      traduccion: 'No aplica.',
      prompting: 'No aplica.',
      imagenes: 'Interpretacion de imagenes medicas (radiografias, MRI).',
      estudio: 'Preparacion para examenes medicos como USMLE y MIR.',
      finanzas: 'No aplica.',
      matematicas: 'No aplica.',
      arte: 'No aplica.',
      video: 'No aplica.',
      audio: 'No aplica.',
      legal: 'No aplica.',
      medicina: 'Nivel experto en razonamiento clinico. Primero en superar al medico promedio en USMLE.',
      productividad: 'No aplica.',
      roleplay: 'No aplica.',
      escritura: 'Redaccion de literatura medica y casos clinicos.',
      investigacion: 'Analisis de ensayos clinicos y revision sistematica.',
    },
  },
  // ─── ROLEPLAY / ESCRITURA ──────────────────────────────────────────────────
  {
    id: 'character-ai',
    name: 'Character.AI',
    company: 'Character.AI',
    description: 'Plataforma de conversacion con personajes de IA. Millones de personajes pre-definidos y herramientas para crear los propios.',
    categories: ['roleplay', 'estudio'],
    badges: ['especializado', 'gratuito'],
    price: 'Gratis / $9.99/mes Plus',
    emoji: '🎭',
    tier: 'A',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'No aplica.',
      marketing: 'No aplica.',
      traduccion: 'No aplica.',
      prompting: 'No aplica.',
      imagenes: 'No aplica.',
      estudio: 'Aprende conversando con personajes historicos o cientificos famosos.',
      finanzas: 'No aplica.',
      matematicas: 'No aplica.',
      arte: 'No aplica.',
      video: 'No aplica.',
      audio: 'No aplica.',
      legal: 'No aplica.',
      medicina: 'No aplica.',
      productividad: 'No aplica.',
      roleplay: 'La plataforma dedicada mas grande para roleplay conversacional con IA.',
      escritura: 'Colabora con personajes para desarrollar historias y dialogos.',
      investigacion: 'No aplica.',
    },
  },
  // ─── ESCRITURA ─────────────────────────────────────────────────────────────
  {
    id: 'sudowrite',
    name: 'Sudowrite',
    company: 'Sudowrite',
    description: 'IA especializada en escritura creativa de largo aliento. Herramientas para novelas, cuentos y desarrollo de personajes.',
    categories: ['escritura', 'arte'],
    badges: ['especializado'],
    price: '$10/mes Hobby',
    emoji: '✍️',
    tier: 'A',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'No aplica.',
      marketing: 'Copy creativo para campanas narrativas.',
      traduccion: 'No aplica.',
      prompting: 'No aplica.',
      imagenes: 'No aplica.',
      estudio: 'No aplica.',
      finanzas: 'No aplica.',
      matematicas: 'No aplica.',
      arte: 'Escritura de narrativas visuales y guiones.',
      video: 'Guiones y story treatments para produccion de video.',
      audio: 'Letras de canciones y narrativa para podcasts.',
      legal: 'No aplica.',
      medicina: 'No aplica.',
      productividad: 'No aplica.',
      roleplay: 'Desarrollo de campanas y worldbuilding para TTRPG.',
      escritura: 'Herramienta definitiva para escritores de ficcion — novelas, cuentos y series.',
      investigacion: 'No aplica.',
    },
  },

  // ─── OPEN SOURCE TOP — HuggingFace / Artificial Analysis ──────────────────
  {
    id: 'llama-4-scout',
    name: 'Llama 4 Scout',
    company: 'Meta',
    description: 'El modelo open-source mas avanzado de Meta. Ventana de contexto de 10M tokens — la mas grande disponible. Multimodal con vision.',
    categories: ['coding', 'estudio', 'escritura', 'investigacion', 'ciencia-datos'],
    badges: ['open-source', 'gratuito', 'multimodal'],
    price: 'Gratis (local) / $0.10 / 1M tokens API',
    emoji: '🦙',
    tier: 'S',
    reasonWhy: {
      coding: 'Contexto de 10M tokens permite analizar repositorios enteros de una vez. Excelente para refactorizacion masiva.',
      'ciencia-datos': 'Procesa datasets enormes y notebooks completos en una sola consulta.',
      marketing: 'Genera estrategias de contenido con analisis de contexto muy amplio.',
      traduccion: 'Traduce documentos completos de gran extension sin perder contexto.',
      prompting: 'Ideal para sistemas de prompts largos y complejos con mucho contexto.',
      imagenes: 'Capacidad de vision para analizar y describir imagenes con detalle.',
      estudio: 'Lee libros completos y genera guias de estudio comprehensivas.',
      finanzas: 'Analiza reportes financieros anuales completos de una sola vez.',
      matematicas: 'Resuelve problemas matematicos con razonamiento solido.',
      arte: 'Analiza y critica obras de arte con vision multimodal.',
      video: 'No genera video directamente.',
      audio: 'No genera audio.',
      legal: 'Lee contratos legales de cientos de paginas sin truncar.',
      medicina: 'Analiza historiales medicos completos y literatura clinica extensa.',
      productividad: 'Automatiza tareas complejas con acceso a contexto muy amplio.',
      roleplay: 'Mantiene worldbuilding coherente en narrativas extremadamente largas.',
      escritura: 'Escribe y edita novelas completas con coherencia de trama y personajes.',
      investigacion: 'Lee docenas de papers de una vez y sintetiza hallazgos.',
    },
  },
  {
    id: 'llama-4-maverick',
    name: 'Llama 4 Maverick',
    company: 'Meta',
    description: 'Version grande de Llama 4 con arquitectura MoE. Supera a GPT-4o en multiples benchmarks siendo completamente open-source.',
    categories: ['coding', 'ciencia-datos', 'matematicas', 'investigacion'],
    badges: ['open-source', 'gratuito', 'razonamiento'],
    price: 'Gratis (local) / $0.20 / 1M tokens API',
    emoji: '🦙',
    tier: 'S',
    reasonWhy: {
      coding: 'Arquitectura MoE optimizada para razonamiento de codigo. Supera a GPT-4o en HumanEval.',
      'ciencia-datos': 'Excelente para analisis estadistico avanzado y pipelines de ML complejos.',
      marketing: 'Genera copy de alta calidad con comprension de contexto de marca.',
      traduccion: 'Traduccion precisa con comprension cultural profunda.',
      prompting: 'Sigue instrucciones complejas con alta fidelidad.',
      imagenes: 'Capacidad de vision para analisis de imagenes.',
      estudio: 'Tutoria avanzada en ciencias y matematicas universitarias.',
      finanzas: 'Modelado financiero cuantitativo y analisis de riesgo.',
      matematicas: 'Razonamiento matematico de nivel universitario con pasos claros.',
      arte: 'Analisis critico de obras de arte y teoria estetica.',
      video: 'No genera video.',
      audio: 'No genera audio.',
      legal: 'Analisis juridico con razonamiento formal solido.',
      medicina: 'Razonamiento clinico diferencial con literatura medica actualizada.',
      productividad: 'Automatizacion de tareas complejas con comprension profunda.',
      roleplay: 'Personajes complejos con psicologia coherente.',
      escritura: 'Escritura creativa de alta calidad con voz literaria propia.',
      investigacion: 'Sintesis de literatura cientifica con razonamiento critico.',
    },
  },
  {
    id: 'glm-5',
    name: 'GLM-5',
    company: 'Zhipu AI',
    description: 'El modelo open-source mejor rankeado en Artificial Analysis (score 50). Razonamiento extendido de clase mundial con capacidades multimodales.',
    categories: ['coding', 'investigacion', 'ciencia-datos', 'matematicas'],
    badges: ['open-source', 'razonamiento', 'mejor-calidad'],
    price: 'Gratis (local) / $0.14 / 1M tokens',
    emoji: '🇨🇳',
    tier: 'S',
    reasonWhy: {
      coding: 'El modelo open-source con mejor score de inteligencia. Sobresale en debugging y arquitectura.',
      'ciencia-datos': 'Razonamiento estadistico profundo con cadenas de pensamiento explicitas.',
      marketing: 'Comprension cultural amplia, especialmente para mercados asiaticos.',
      traduccion: 'Excepcional en traduccion chino-espanol e ingles con matices culturales.',
      prompting: 'Razona sobre la estructura optima de los prompts antes de responder.',
      imagenes: 'Capacidades multimodales para analisis visual avanzado.',
      estudio: 'Explica cada paso del razonamiento para maximo aprendizaje.',
      finanzas: 'Modelado cuantitativo y analisis de mercados financieros complejos.',
      matematicas: 'Nivel olympiade en benchmarks matematicos. Demostraciones formales precisas.',
      arte: 'Analisis artistico con perspectiva cultural global.',
      video: 'No genera video directamente.',
      audio: 'No genera audio.',
      legal: 'Razonamiento juridico formal con precedentes y argumentacion logica.',
      medicina: 'Razonamiento clinico diferencial de alta precision.',
      productividad: 'Automatizacion de workflows con comprension profunda del contexto.',
      roleplay: 'Narrativas complejas con personajes culturalmente ricos.',
      escritura: 'Escritura academica y creativa con rigor intelectual.',
      investigacion: 'Sintesis de investigacion con razonamiento critico sobresaliente.',
    },
  },
  {
    id: 'kimi-k2',
    name: 'Kimi K2.5',
    company: 'Moonshot AI',
    description: '#2 open-source en Artificial Analysis (score 47). Arquitectura MoE de 1T parametros con razonamiento extendido y acceso a herramientas.',
    categories: ['investigacion', 'coding', 'escritura', 'ciencia-datos'],
    badges: ['open-source', 'razonamiento', 'mejor-calidad'],
    price: 'Gratis (local) / $0.15 / 1M tokens',
    emoji: '🌙',
    tier: 'S',
    reasonWhy: {
      coding: '1T parametros MoE con uso de herramientas (browser, code interpreter). Excelente en agentes de codigo.',
      'ciencia-datos': 'Capacidad de usar herramientas externas para analisis de datos en tiempo real.',
      marketing: 'Investigacion de mercado con acceso a herramientas web integradas.',
      traduccion: 'Traduccion con contexto cultural profundo, especialmente en asiatico.',
      prompting: 'Arquitectura de agente que optimiza el uso de herramientas automaticamente.',
      imagenes: 'Analisis visual con integracion de herramientas externas.',
      estudio: 'Puede buscar informacion actualizada para complementar el aprendizaje.',
      finanzas: 'Analisis financiero con acceso a datos de mercado actualizados.',
      matematicas: 'Usa code interpreter para verificar resultados matematicos automaticamente.',
      arte: 'Investigacion y analisis artistico con acceso a referencias externas.',
      video: 'No genera video directamente.',
      audio: 'No genera audio.',
      legal: 'Busca precedentes legales y normativas actualizadas automaticamente.',
      medicina: 'Accede a literatura medica actualizada en tiempo real.',
      productividad: 'Agente que usa multiples herramientas para completar tareas complejas.',
      roleplay: 'Worldbuilding rico con investigacion en tiempo real.',
      escritura: 'Escritura informada con capacidad de investigar datos en tiempo real.',
      investigacion: 'El mejor open-source para investigacion — usa herramientas web de forma autonoma.',
    },
  },
  {
    id: 'qwen35-397b',
    name: 'Qwen3.5 397B A17B',
    company: 'Alibaba',
    description: '#3 open-source en AA (score 45). Modelo MoE masivo de Alibaba con razonamiento. Sobresale en codigo, matematicas y multiples idiomas.',
    categories: ['coding', 'matematicas', 'ciencia-datos', 'traduccion'],
    badges: ['open-source', 'razonamiento', 'mejor-calidad'],
    price: 'Gratis (local) / $0.18 / 1M tokens',
    emoji: '🔶',
    tier: 'S',
    reasonWhy: {
      coding: 'Arquitectura MoE con 397B parametros totales. Excelente en Python, Java y C++ con razonamiento profundo.',
      'ciencia-datos': 'Muy fuerte en ciencia de datos, estadistica y modelado cuantitativo.',
      marketing: 'Genera contenido para multiples idiomas y mercados asiaticos.',
      traduccion: 'Excepcional en chino, japones, coreano, espanol e ingles con alta precision.',
      prompting: 'Razonamiento chain-of-thought de alta calidad en multiples idiomas.',
      imagenes: 'Analisis visual multilingue.',
      estudio: 'Tutoria en multiples idiomas con explicaciones paso a paso.',
      finanzas: 'Analisis financiero cuantitativo con razonamiento formal.',
      matematicas: 'Nivel olympiade en matematicas. Uno de los mejores open-source en benchmarks matematicos.',
      arte: 'Comprension estetica y cultural desde perspectiva asiatica y global.',
      video: 'No genera video.',
      audio: 'No genera audio.',
      legal: 'Analisis juridico en multiples idiomas y jurisdicciones.',
      medicina: 'Literatura medica en multiples idiomas con razonamiento clinico.',
      productividad: 'Automatizacion multilingue de alto rendimiento.',
      roleplay: 'Narrativas en multiples idiomas con coherencia cultural.',
      escritura: 'Escritura creativa en chino, espanol, ingles y otros idiomas con fluidez nativa.',
      investigacion: 'Investigacion en multiples idiomas y contextos culturales.',
    },
  },
  {
    id: 'llama-33-70b',
    name: 'Llama 3.3 70B',
    company: 'Meta',
    description: 'El modelo open-source de 70B mas equilibrado. Excelente calidad/recurso, ejecutable en hardware consumer y disponible via API economica.',
    categories: ['coding', 'estudio', 'escritura', 'productividad'],
    badges: ['open-source', 'gratuito', 'mas-barato'],
    price: 'Gratis (local 48GB VRAM) / $0.09 / 1M tokens',
    emoji: '🦙',
    tier: 'A',
    reasonWhy: {
      coding: 'Excelente para tareas de codigo en hardware local. La mejor relacion calidad/costo en open-source 70B.',
      'ciencia-datos': 'Bueno para analisis de datos en entornos privados sin enviar datos a la nube.',
      marketing: 'Genera contenido de marketing de calidad con deployment local.',
      traduccion: 'Traduccion de calidad solida en los idiomas principales.',
      prompting: 'Sigue instrucciones con buena consistencia para su tamano.',
      imagenes: 'No genera imagenes.',
      estudio: 'Tutoria efectiva en materias universitarias con disponibilidad offline.',
      finanzas: 'Analisis financiero local sin enviar datos sensibles a APIs externas.',
      matematicas: 'Resuelve problemas de calculo y algebra con buena precision.',
      arte: 'Analisis y critica artistica de calidad solida.',
      video: 'No genera video.',
      audio: 'No genera audio.',
      legal: 'Analisis de documentos legales en entorno completamente privado.',
      medicina: 'Procesamiento de datos medicos sensibles sin salir de la infraestructura propia.',
      productividad: 'Automatizacion local sin dependencia de APIs externas ni costos variables.',
      roleplay: 'Conversaciones de rol con privacidad total al ejecutar localmente.',
      escritura: 'Escritura creativa solida con buena coherencia narrativa.',
      investigacion: 'Investigacion en entornos air-gapped o con alta privacidad.',
    },
  },
  {
    id: 'mistral-large',
    name: 'Mistral Large 3',
    company: 'Mistral AI',
    description: 'El modelo europeo de referencia. Lider en frances y espanol. Excelente para razonamiento juridico, codigo y contextos multilingues europeos.',
    categories: ['coding', 'legal', 'escritura', 'traduccion', 'investigacion'],
    badges: ['mejor-calidad', 'razonamiento'],
    price: '$2 / 1M tokens',
    emoji: '🇫🇷',
    tier: 'A',
    reasonWhy: {
      coding: 'Fuerte en Python, JavaScript y TypeScript. Bueno para proyectos que requieren compliance europeo.',
      'ciencia-datos': 'Solido para analisis de datos con consciencia de regulaciones GDPR.',
      marketing: 'Domina el espanol y frances con matices culturales europeos nativos.',
      traduccion: 'El mejor para traducciones frances-espanol-ingles con precision legal y cultural.',
      prompting: 'Sigue instrucciones tecnicas con alta precision y consistencia.',
      imagenes: 'No genera imagenes.',
      estudio: 'Explicaciones academicas con rigor intelectual europeo.',
      finanzas: 'Conocimiento de regulaciones financieras europeas (MiFID, GDPR, ESG).',
      matematicas: 'Razonamiento matematico solido con explicaciones claras.',
      arte: 'Comprension profunda del arte y la cultura europea.',
      video: 'No genera video.',
      audio: 'No genera audio.',
      legal: 'Especializado en derecho europeo (GDPR, derecho frances, espanol, italiano). Alta precision juridica.',
      medicina: 'Literatura medica europea con terminologia clinica correcta.',
      productividad: 'Automatizacion con consciencia de compliance europeo.',
      roleplay: 'Narrativas con riqueza cultural europea.',
      escritura: 'Escritura literaria con influencia europea. Excelente en espanol y frances.',
      investigacion: 'Investigacion con fuentes academicas europeas y rigor intelectual.',
    },
  },
  {
    id: 'phi-4',
    name: 'Phi-4 Mini',
    company: 'Microsoft',
    description: 'Modelo compacto de Microsoft con rendimiento sorprendente para su tamano. Ideal para educacion, dispositivos con recursos limitados y apps moviles.',
    categories: ['estudio', 'coding', 'matematicas', 'productividad'],
    badges: ['open-source', 'gratuito', 'mas-barato'],
    price: 'Gratis (muy liviano, 4-8GB RAM)',
    emoji: '🔷',
    tier: 'A',
    reasonWhy: {
      coding: 'Optimizado para tareas de codigo en dispositivos de bajo recurso. Perfecto para IDE plugins.',
      'ciencia-datos': 'Analisis de datos rapido en hardware limitado o edge computing.',
      marketing: 'No es su especialidad principal.',
      traduccion: 'Traduccion funcional en los idiomas principales.',
      prompting: 'Eficiente en tareas estructuradas con prompts claros.',
      imagenes: 'No genera imagenes.',
      estudio: 'Perfecto para apps educativas en dispositivos moviles. Rapido y economico.',
      finanzas: 'Calculo financiero basico con muy baja latencia.',
      matematicas: 'Destaca en matematicas para su tamano — entrenado especialmente en datos matematicos.',
      arte: 'Limitado para tareas creativas complejas.',
      video: 'No genera video.',
      audio: 'No genera audio.',
      legal: 'Analisis legal basico en dispositivos locales.',
      medicina: 'Soporte medico basico offline en entornos con conectividad limitada.',
      productividad: 'Automatizacion ultra-ligera para dispositivos edge e IoT.',
      roleplay: 'Conversaciones simples de rol con muy baja latencia.',
      escritura: 'Escritura y edicion basica rapida.',
      investigacion: 'Respuestas factuales rapidas en dispositivos con recursos limitados.',
    },
  },
  {
    id: 'gemma-3-27b',
    name: 'Gemma 3 27B',
    company: 'Google',
    description: 'El modelo open-source de Google con capacidades multimodales. Excelente calidad ejecutable en una sola GPU consumer de alta gama.',
    categories: ['estudio', 'coding', 'escritura', 'ciencia-datos'],
    badges: ['open-source', 'gratuito', 'multimodal'],
    price: 'Gratis (local ~20GB VRAM) / $0.10 / 1M tokens',
    emoji: '💎',
    tier: 'A',
    reasonWhy: {
      coding: 'Modelo open-source de Google con buen desempeno en codigo Python y JavaScript.',
      'ciencia-datos': 'Integra vision para analisis de graficas y tablas desde imagenes.',
      marketing: 'Genera contenido con capacidad de analizar imagenes de marca.',
      traduccion: 'Solido en los idiomas principales con comprension contextual.',
      prompting: 'Sigue instrucciones complejas con la calidad que caracteriza a Google.',
      imagenes: 'Analiza imagenes con detalle — capacidad multimodal nativa.',
      estudio: 'Explica conceptos con diagramas y analiza imagenes de libros de texto.',
      finanzas: 'Analiza graficos financieros desde imagenes con precision.',
      matematicas: 'Interpreta ecuaciones escritas a mano desde imagenes.',
      arte: 'Analisis visual de obras de arte con comprension estetica.',
      video: 'No genera video.',
      audio: 'No genera audio.',
      legal: 'Lectura de documentos legales escaneados (PDF imagen).',
      medicina: 'Interpreta imagenes medicas y diagramas anatomicos.',
      productividad: 'Automatizacion con procesamiento visual incluido.',
      roleplay: 'Conversaciones con comprension de imagenes compartidas.',
      escritura: 'Escritura creativa con inspiracion visual desde imagenes.',
      investigacion: 'Analiza figuras y graficas de papers cientificos.',
    },
  },
  {
    id: 'command-r-plus',
    name: 'Command R+',
    company: 'Cohere',
    description: 'El modelo de Cohere especializado en RAG (Retrieval-Augmented Generation) y uso empresarial. Ideal para conectar IA con bases de datos propias.',
    categories: ['marketing', 'investigacion', 'legal', 'productividad'],
    badges: ['especializado', 'razonamiento'],
    price: '$2.50 / 1M tokens',
    emoji: '🔗',
    tier: 'A',
    reasonWhy: {
      coding: 'Util para generar codigo que interactua con bases de datos y APIs.',
      'ciencia-datos': 'RAG para conectar con datasets y documentacion tecnica propios.',
      marketing: 'Genera contenido basado en tus propias guias de marca y datos de clientes.',
      traduccion: 'No especializado en traduccion.',
      prompting: 'Arquitectura optimizada para grounding en documentos propios.',
      imagenes: 'No genera imagenes.',
      estudio: 'Conecta con tu propia base de conocimiento para respuestas precisas.',
      finanzas: 'RAG sobre reportes financieros propios con citas precisas.',
      matematicas: 'No es su especialidad.',
      arte: 'No aplica directamente.',
      video: 'No genera video.',
      audio: 'No genera audio.',
      legal: 'RAG sobre tu base de precedentes legales. Respuestas con citas exactas del documento.',
      medicina: 'Conecta con bases de datos clinicas propias con respuestas verificables.',
      productividad: 'El mejor para empresas que quieren IA sobre sus propios documentos internos.',
      roleplay: 'No es su especialidad.',
      escritura: 'Genera contenido basado en el estilo y tono de tus documentos existentes.',
      investigacion: 'RAG de clase mundial — conecta con tu biblioteca de papers y cita fuentes exactas.',
    },
  },
  // ─── LLMs PROPIETARIOS NUEVOS ─────────────────────────────────────────────
  {
    id: 'o3-mini',
    name: 'o3-mini',
    company: 'OpenAI',
    description: 'Modelo de razonamiento eficiente de OpenAI. Supera a o1 en velocidad y costo manteniendo el mismo nivel en matematicas y codigo.',
    categories: ['matematicas', 'coding', 'ciencia-datos', 'finanzas'],
    badges: ['razonamiento', 'mas-barato', 'mas-rapido'],
    price: '$1.10 / 1M tokens',
    emoji: '🔢',
    tier: 'S',
    reasonWhy: {
      coding: 'Razonamiento profundo para debugging complejo a menor costo que o1. Ideal para algoritmos avanzados.',
      'ciencia-datos': 'Deriva formulas estadisticas y revisa modelos ML con razonamiento paso a paso.',
      marketing: 'No su especialidad principal.',
      traduccion: 'No especializado.',
      prompting: 'Razona sobre la estructura optima del prompt antes de responder.',
      imagenes: 'No genera imagenes.',
      estudio: 'Explica cada paso del razonamiento matematico para maximo aprendizaje.',
      finanzas: 'Modelos cuantitativos complejos y calculo de derivados financieros.',
      matematicas: 'Supera a o1 en eficiencia. Resuelve problemas de nivel competicion matematica.',
      arte: 'No aplica.',
      video: 'No genera video.',
      audio: 'No genera audio.',
      legal: 'Razonamiento juridico formal con cadenas de argumentacion rigurosas.',
      medicina: 'Diagnostico diferencial con razonamiento clinico paso a paso.',
      productividad: 'Automatizacion de tareas que requieren razonamiento complejo a bajo costo.',
      roleplay: 'No su especialidad.',
      escritura: 'Escritura tecnica y academica rigurosa.',
      investigacion: 'Razonamiento cientifico para hipotesis y analisis de resultados.',
    },
  },
  {
    id: 'o1',
    name: 'o1',
    company: 'OpenAI',
    description: 'El modelo de razonamiento original de OpenAI. Piensa durante minutos antes de responder. Referencia en matematicas dificiles, codigo complejo y ciencia.',
    categories: ['matematicas', 'legal', 'finanzas', 'ciencia-datos', 'investigacion'],
    badges: ['razonamiento', 'mejor-calidad'],
    price: '$15 / 1M tokens',
    emoji: '⭕',
    tier: 'S',
    reasonWhy: {
      coding: 'Arquitecturas de software complejas y algoritmos de alto nivel con verificacion interna.',
      'ciencia-datos': 'Modelado estadistico avanzado y diseno de experimentos con razonamiento formal.',
      marketing: 'No su especialidad principal.',
      traduccion: 'No especializado.',
      prompting: 'Razona internamente sobre la mejor respuesta antes de generar output.',
      imagenes: 'No genera imagenes.',
      estudio: 'Tutoria en matematicas y fisica avanzadas con demostraciones rigurosas.',
      finanzas: 'El mejor para modelos cuantitativos complejos, pricing de derivados y risk management.',
      matematicas: 'Referencia absoluta para matematicas de competicion y demostraciones formales.',
      arte: 'Analisis critico con profundidad filosofica.',
      video: 'No genera video.',
      audio: 'No genera audio.',
      legal: 'Razonamiento juridico de nivel experto. Analiza precedentes y construye argumentaciones complejas.',
      medicina: 'Razonamiento diagnostico de nivel especialista con consideracion de raridades clinicas.',
      productividad: 'Resuelve problemas de optimizacion empresarial complejos.',
      roleplay: 'No su especialidad.',
      escritura: 'Ensayos academicos y argumentativos de alta complejidad.',
      investigacion: 'Ideal para investigacion que requiere razonamiento hipotetico-deductivo riguroso.',
    },
  },
  {
    id: 'grok-3',
    name: 'Grok 3',
    company: 'xAI',
    description: 'Modelo de Elon Musk con acceso a datos de X/Twitter en tiempo real. Fuerte en analisis de tendencias, mercados y noticias actualizadas al instante.',
    categories: ['investigacion', 'finanzas', 'marketing', 'productividad'],
    badges: ['mejor-calidad', 'razonamiento', 'especializado'],
    price: 'Incluido en X Premium+ ($16/mes)',
    emoji: '𝕏',
    tier: 'S',
    reasonWhy: {
      coding: 'Buen rendimiento en codigo con acceso a documentacion y repositorios recientes.',
      'ciencia-datos': 'Analiza tendencias de datos en tiempo real desde redes sociales.',
      marketing: 'Acceso a tendencias virales de X/Twitter en tiempo real para campanas actualizadas.',
      traduccion: 'Traduccion solida con contexto cultural actualizado.',
      prompting: 'Sigue instrucciones con alta fidelidad y razonamiento profundo.',
      imagenes: 'Genera y analiza imagenes con capacidades multimodales.',
      estudio: 'Informacion actualizada para estudios que requieren datos recientes.',
      finanzas: 'Analisis de sentimiento de mercado en tiempo real desde X. Noticias financieras al instante.',
      matematicas: 'Razonamiento matematico solido con cadenas de pensamiento.',
      arte: 'Tendencias artisticas y culturales actualizadas en tiempo real.',
      video: 'No genera video directamente.',
      audio: 'No genera audio.',
      legal: 'Noticias juridicas y cambios regulatorios actualizados al instante.',
      medicina: 'Noticias medicas y actualizaciones clinicas en tiempo real.',
      productividad: 'Automatizacion con acceso a informacion actualizada sin necesidad de busquedas manuales.',
      roleplay: 'Contexto cultural y referencias actuales integradas en narrativas.',
      escritura: 'Escritura informada con datos y tendencias en tiempo real.',
      investigacion: 'Unico con acceso a X/Twitter en tiempo real. El mejor para investigacion de tendencias y opinion publica.',
    },
  },
  {
    id: 'gemini-31-pro',
    name: 'Gemini 3.1 Pro Preview',
    company: 'Google',
    description: '#1 en Artificial Analysis Intelligence Index (score 57). El modelo mas inteligente disponible actualmente segun multiples benchmarks.',
    categories: ['coding', 'investigacion', 'matematicas', 'ciencia-datos', 'escritura'],
    badges: ['mejor-calidad', 'razonamiento', 'multimodal'],
    price: '$7 / 1M tokens (estimado)',
    emoji: '🥇',
    tier: 'S',
    reasonWhy: {
      coding: 'El modelo mas inteligente del mercado. Arquitectura, debugging y optimizacion de sistemas complejos.',
      'ciencia-datos': 'Analisis multimodal de datos con el mayor nivel de inteligencia disponible.',
      marketing: 'Estrategias de marketing de nivel experto con analisis profundo.',
      traduccion: 'Traduccion con la mayor comprension contextual y cultural disponible.',
      prompting: 'El modelo ideal para disenar sistemas de prompts de maxima complejidad.',
      imagenes: 'Vision multimodal de clase mundial para analisis visual avanzado.',
      estudio: 'El tutor mas avanzado disponible para cualquier materia academica.',
      finanzas: 'Analisis financiero con el mayor nivel de razonamiento disponible.',
      matematicas: 'Referencia junto a GPT-5.4 para matematicas avanzadas y demostraciones formales.',
      arte: 'Analisis y critica artistica con la mayor profundidad intelectual.',
      video: 'Analisis de video completo frame por frame con contexto amplio.',
      audio: 'Transcripcion y analisis de audio con alta precision.',
      legal: 'Razonamiento juridico de nivel experto con el modelo mas inteligente del mercado.',
      medicina: 'Razonamiento clinico diferencial con el mayor nivel de inteligencia disponible.',
      productividad: 'Automatizacion de las tareas mas complejas con minima supervision.',
      roleplay: 'Narrativas de la maxima complejidad con personajes y worldbuilding excepcionales.',
      escritura: 'Escritura literaria con el nivel de sofisticacion mas alto disponible.',
      investigacion: 'El mejor modelo para investigacion cientifica y academica de alto nivel.',
    },
  },
  {
    id: 'gpt-54',
    name: 'GPT-5.4',
    company: 'OpenAI',
    description: '#2 en Artificial Analysis (score 57). La version mas avanzada de GPT-5 con razonamiento extendido y capacidades multimodales completas.',
    categories: ['coding', 'escritura', 'finanzas', 'investigacion', 'ciencia-datos'],
    badges: ['mejor-calidad', 'razonamiento', 'multimodal'],
    price: '$30 / 1M tokens (estimado)',
    emoji: '🏆',
    tier: 'S',
    reasonWhy: {
      coding: 'La version mas avanzada de OpenAI. Arquitecturas de sistemas de la maxima complejidad.',
      'ciencia-datos': 'Analisis cientifico con razonamiento extendido y verificacion de resultados.',
      marketing: 'Estrategia de marketing con el mayor nivel de sofisticacion disponible.',
      traduccion: 'Traduccion con comprension contextual y cultural maxima.',
      prompting: 'Modelo de referencia para disenar los sistemas de prompts mas avanzados.',
      imagenes: 'Vision y generacion de imagenes de clase mundial.',
      estudio: 'El tutor mas avanzado disponible para educacion universitaria y postgrado.',
      finanzas: 'Analisis financiero de nivel institucional con razonamiento cuantitativo avanzado.',
      matematicas: 'Nivel olympiade con demostraciones formales y verificacion automatica.',
      arte: 'Critica y creacion artistica con el mayor nivel intelectual disponible.',
      video: 'Analisis y descripcion de video de alta complejidad.',
      audio: 'Transcripcion y analisis de audio de alta precision.',
      legal: 'Analisis juridico de maxima complejidad con razonamiento formal avanzado.',
      medicina: 'El nivel mas alto de razonamiento clinico disponible en IA.',
      productividad: 'Automatizacion de los flujos de trabajo mas complejos.',
      roleplay: 'Las narrativas mas complejas y personajes mas ricos disponibles en IA.',
      escritura: 'Escritura literaria de la maxima sofisticacion y calidad.',
      investigacion: 'Investigacion cientifica con el mayor nivel de razonamiento e inteligencia.',
    },
  },
  {
    id: 'nova-pro',
    name: 'Amazon Nova Pro',
    company: 'AWS',
    description: 'Modelo multimodal de Amazon integrado en AWS Bedrock. Ideal para empresas con infraestructura en AWS. Excelente precio/rendimiento empresarial.',
    categories: ['productividad', 'finanzas', 'legal', 'ciencia-datos'],
    badges: ['multimodal', 'especializado', 'mas-barato'],
    price: '$0.80 / 1M tokens',
    emoji: '🟠',
    tier: 'A',
    reasonWhy: {
      coding: 'Bueno para proyectos en el ecosistema AWS (Lambda, S3, Bedrock).',
      'ciencia-datos': 'Integrado nativamente con SageMaker y servicios de datos de AWS.',
      marketing: 'Genera contenido para campanas con integracion AWS nativa.',
      traduccion: 'Traduccion solida con integracion en Amazon Translate.',
      prompting: 'Optimizado para el ecosistema de herramientas de Bedrock.',
      imagenes: 'Vision multimodal para analisis de imagenes y documentos.',
      estudio: 'No su especialidad principal.',
      finanzas: 'Integrado con servicios financieros de AWS y compliance empresarial.',
      matematicas: 'Calculo y analisis cuantitativo de nivel solido.',
      arte: 'No especializado.',
      video: 'Analisis de video con integracion Rekognition.',
      audio: 'Integracion con Amazon Transcribe para procesamiento de audio.',
      legal: 'Analisis de contratos con compliance y auditoria AWS integrados.',
      medicina: 'Integracion con servicios de salud de AWS y compliance HIPAA.',
      productividad: 'La opcion mas natural para empresas con infraestructura AWS. Sin fricciones de integracion.',
      roleplay: 'No su especialidad.',
      escritura: 'Generacion de contenido a escala con infraestructura AWS.',
      investigacion: 'Analisis de grandes volumenes de datos con integracion S3 y Athena.',
    },
  },
  // ─── IMAGENES NUEVAS ──────────────────────────────────────────────────────
  {
    id: 'adobe-firefly',
    name: 'Adobe Firefly 3',
    company: 'Adobe',
    description: 'El unico modelo de imagenes entrenado exclusivamente con contenido con licencia. Uso comercial 100% seguro, integrado en Photoshop e Illustrator.',
    categories: ['imagenes', 'arte', 'marketing', 'productividad'],
    badges: ['especializado', 'mejor-calidad'],
    price: 'Incluido en Creative Cloud ($54.99/mes)',
    emoji: '🔥',
    tier: 'A',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'No aplica.',
      marketing: 'El unico con uso comercial legalmente seguro. Indispensable para agencias y marcas.',
      traduccion: 'No aplica.',
      prompting: 'Integrado en el flujo de trabajo de Adobe con controles visuales intuitivos.',
      imagenes: 'Unico entrenado con contenido con licencia. Seguro para uso comercial sin riesgos legales.',
      estudio: 'Genera material educativo visual con derechos claros.',
      finanzas: 'Genera infografias financieras con activos de stock con licencia.',
      matematicas: 'No aplica.',
      arte: 'Integrado en Photoshop para flujo de trabajo creativo profesional.',
      video: 'Genera efectos y assets de video dentro de Premiere Pro.',
      audio: 'No aplica.',
      legal: 'La unica opcion sin riesgo de infraccion de derechos de autor en generacion de imagenes.',
      medicina: 'Ilustraciones medicas con activos con licencia para publicaciones.',
      productividad: 'Flujo integrado en Creative Cloud — sin salir de Photoshop o Illustrator.',
      roleplay: 'Assets visuales con derechos claros para publicaciones de campanas de rol.',
      escritura: 'Portadas e ilustraciones con derechos de uso comercial garantizados.',
      investigacion: 'Figuras e ilustraciones para publicaciones academicas sin problemas de copyright.',
    },
  },
  {
    id: 'ideogram-2',
    name: 'Ideogram 2',
    company: 'Ideogram',
    description: 'El modelo especializado en texto dentro de imagenes. Logos, carteles, tipografia y diseño grafico con texto legible y preciso.',
    categories: ['imagenes', 'arte', 'marketing'],
    badges: ['especializado', 'mejor-calidad'],
    price: '$7/mes Basic / $16/mes Plus',
    emoji: '🅰️',
    tier: 'A',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'No aplica.',
      marketing: 'El mejor para crear logos, banners y carteles con texto integrado de forma legible.',
      traduccion: 'No aplica.',
      prompting: 'Entiende instrucciones de tipografia y composicion grafica con precision.',
      imagenes: 'Resuelve el problema historico de los LLMs con el texto en imagenes. Texto perfecto y legible.',
      estudio: 'Genera infografias educativas con etiquetas y texto precisos.',
      finanzas: 'Crea infografias financieras con numeros y texto legibles.',
      matematicas: 'No aplica.',
      arte: 'Arte tipografico, carteles y diseño grafico con texto como elemento central.',
      video: 'No genera video.',
      audio: 'No aplica.',
      legal: 'No aplica.',
      medicina: 'Diagramas y figuras medicas con etiquetas precisas y legibles.',
      productividad: 'Genera presentaciones, infografias y materiales con texto integrado.',
      roleplay: 'Escudos, mapas y documentos ficticios con texto coherente.',
      escritura: 'Portadas de libros con tipografia perfecta.',
      investigacion: 'Figuras cientificas con etiquetas y leyendas precisas.',
    },
  },
  {
    id: 'leonardo-ai',
    name: 'Leonardo AI',
    company: 'Leonardo',
    description: 'Plataforma de generacion de imagenes especializada en game art, concept art y character design. Usado por estudios de videojuegos profesionales.',
    categories: ['imagenes', 'arte', 'roleplay'],
    badges: ['especializado', 'mas-barato'],
    price: 'Gratis (150 tokens/dia) / $10/mes Apprentice',
    emoji: '🎮',
    tier: 'A',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'No aplica.',
      marketing: 'Assets visuales para videojuegos, apps y productos digitales.',
      traduccion: 'No aplica.',
      prompting: 'Sistema de prompts visual con referencias de estilo (LoRAs personalizados).',
      imagenes: 'Especializado en estilos de videojuegos, fantasy art y concept art con consistencia de personajes.',
      estudio: 'Ilustraciones educativas gamificadas y atractivas.',
      finanzas: 'No aplica.',
      matematicas: 'No aplica.',
      arte: 'El estandar de la industria para estudios de videojuegos y artistas de concepto.',
      video: 'Genera secuencias de animacion para personajes de juegos.',
      audio: 'No aplica.',
      legal: 'No aplica.',
      medicina: 'Ilustraciones anatomicas con estilo grafico atractivo.',
      productividad: 'Generacion masiva de assets para proyectos de juegos.',
      roleplay: 'El mejor para generar personajes, mapas y assets visuales de campanas de rol.',
      escritura: 'Ilustraciones de personajes y mundos para novelas de fantasia.',
      investigacion: 'No aplica.',
    },
  },
  // ─── VIDEO NUEVO ──────────────────────────────────────────────────────────
  {
    id: 'sora',
    name: 'Sora',
    company: 'OpenAI',
    description: 'El modelo de generacion de video de OpenAI que revoluciono la industria. Genera videos de hasta 1 minuto con coherencia cinematografica.',
    categories: ['video', 'arte', 'marketing'],
    badges: ['mejor-calidad', 'especializado'],
    price: 'Incluido en ChatGPT Plus ($20/mes)',
    emoji: '🎞️',
    tier: 'S',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'Genera visualizaciones animadas de datos y procesos.',
      marketing: 'El nombre mas reconocido en video IA. Videos publicitarios con coherencia narrativa.',
      traduccion: 'No aplica.',
      prompting: 'Entiende prompts cinematograficos complejos con camara, iluminacion y accion.',
      imagenes: 'Genera frames de altisima calidad como imagenes estaticas.',
      estudio: 'Videos educativos animados con calidad cinematografica.',
      finanzas: 'No aplica directamente.',
      matematicas: 'No aplica.',
      arte: 'Cortometrajes y video arte con narrativa coherente de hasta 1 minuto.',
      video: 'El modelo referencia de OpenAI. Videos de alta calidad con coherencia temporal excepcional.',
      audio: 'No genera audio por defecto (sin banda sonora propia).',
      legal: 'No aplica.',
      medicina: 'Animaciones de procesos biologicos y procedimientos medicos.',
      productividad: 'Generacion de demos de producto y prototipos de video rapidamente.',
      roleplay: 'Trailers y cutscenes cinematograficas para campanas de rol.',
      escritura: 'Adapta escenas escritas a video con alta fidelidad.',
      investigacion: 'Visualizaciones animadas de datos y fenomenos cientificos.',
    },
  },
  {
    id: 'pika-2',
    name: 'Pika Labs 2.0',
    company: 'Pika',
    description: 'Generacion de video corto para redes sociales. Especializado en efectos creativos, transiciones y animacion de imagenes estaticas.',
    categories: ['video', 'marketing', 'arte'],
    badges: ['especializado', 'mas-barato'],
    price: 'Gratis (30 videos/mes) / $8/mes Basic',
    emoji: '📱',
    tier: 'A',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'No aplica.',
      marketing: 'Especializado en videos cortos para Instagram, TikTok y Reels. Efectos visuales creativos.',
      traduccion: 'No aplica.',
      prompting: 'Prompts de video orientados a efectos y estilos creativos.',
      imagenes: 'Anima imagenes estaticas con movimiento natural.',
      estudio: 'Videos cortos y atractivos para contenido educativo en redes.',
      finanzas: 'No aplica.',
      matematicas: 'No aplica.',
      arte: 'Efectos artisticos y transiciones creativas para video arte.',
      video: 'El mejor para video corto con efectos creativos y animacion de fotos estaticas para redes sociales.',
      audio: 'No genera audio.',
      legal: 'No aplica.',
      medicina: 'No aplica.',
      productividad: 'Videos de producto rapidos para marketing en redes sociales.',
      roleplay: 'No aplica.',
      escritura: 'No aplica.',
      investigacion: 'No aplica.',
    },
  },
  // ─── AUDIO NUEVO ─────────────────────────────────────────────────────────
  {
    id: 'udio',
    name: 'Udio',
    company: 'Udio',
    description: 'Generacion de musica con IA de alta calidad. Fuerte en musica electronica, hip-hop y generos contemporaneos. Genera canciones completas con voz.',
    categories: ['audio', 'arte', 'marketing'],
    badges: ['especializado', 'mas-barato'],
    price: 'Gratis (600 credits/mes) / $7/mes Standard',
    emoji: '🎧',
    tier: 'A',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'No aplica.',
      marketing: 'Genera jingles y musica para contenido de marca con gran variedad de generos.',
      traduccion: 'No aplica.',
      prompting: 'Prompts musicales detallados para genero, mood, instrumentos y estructura.',
      imagenes: 'No aplica.',
      estudio: 'Crea canciones mnemonicas y musica de fondo para sesiones de estudio.',
      finanzas: 'No aplica.',
      matematicas: 'No aplica.',
      arte: 'Composicion musical completa en generos contemporaneos. Alternativa a Suno con mayor variedad.',
      video: 'Genera bandas sonoras originales para cortometrajes y videos.',
      audio: 'Especializado en musica electronica, hip-hop y generos modernos. Mayor variedad de estilos que Suno.',
      legal: 'No aplica.',
      medicina: 'No aplica.',
      productividad: 'Genera musica de fondo para presentaciones y contenido corporativo.',
      roleplay: 'Temas musicales para ambientacion de partidas de rol.',
      escritura: 'Bandas sonoras para audiolibros y podcasts narrativos.',
      investigacion: 'No aplica.',
    },
  },
  // ─── PRODUCTIVIDAD / HERRAMIENTAS ─────────────────────────────────────────
  {
    id: 'cursor',
    name: 'Cursor',
    company: 'Anysphere',
    description: 'El IDE con IA mas popular entre desarrolladores. Combina un editor de codigo completo con Claude y GPT integrados. Reemplaza a Copilot en productividad.',
    categories: ['coding', 'productividad'],
    badges: ['especializado', 'mejor-calidad'],
    price: 'Gratis (basico) / $20/mes Pro',
    emoji: '⌨️',
    tier: 'S',
    reasonWhy: {
      coding: 'El mejor IDE con IA del mercado. Edicion en linea, chat con codebase, composicion multiarchivo y debugging integrado.',
      'ciencia-datos': 'Edicion de notebooks y scripts Python con contexto de todo el proyecto.',
      marketing: 'No aplica directamente.',
      traduccion: 'No aplica.',
      prompting: 'Aprende a escribir prompts tecnicos viendo como Cursor los estructura internamente.',
      imagenes: 'No genera imagenes.',
      estudio: 'Aprende codigo con un tutor integrado en el editor mientras programas.',
      finanzas: 'Desarrollo de modelos financieros y scripts de analisis con IA integrada.',
      matematicas: 'Escribe y depura algoritmos matematicos con asistencia inline.',
      arte: 'No aplica.',
      video: 'No aplica.',
      audio: 'No aplica.',
      legal: 'No aplica.',
      medicina: 'Desarrollo de software medico con IA que entiende el codebase completo.',
      productividad: 'El cambio de paradigma en productividad de desarrollo. Composicion multiarchivo con un solo prompt.',
      roleplay: 'No aplica.',
      escritura: 'No aplica.',
      investigacion: 'Desarrollo de herramientas de analisis e investigacion con IA integrada.',
    },
  },
  {
    id: 'ms-copilot',
    name: 'Microsoft Copilot',
    company: 'Microsoft',
    description: 'IA integrada en todo Office 365. Redacta en Word, analiza en Excel, resume en Teams y genera presentaciones en PowerPoint automaticamente.',
    categories: ['productividad', 'escritura', 'finanzas', 'marketing'],
    badges: ['especializado', 'multimodal'],
    price: 'Incluido en Microsoft 365 Copilot ($30/usuario/mes)',
    emoji: '🪟',
    tier: 'A',
    reasonWhy: {
      coding: 'Asistencia de codigo en VS Code y GitHub Copilot integrados.',
      'ciencia-datos': 'Analisis de datos en Excel con Python integrado y visualizaciones automaticas.',
      marketing: 'Genera presentaciones de marketing en PowerPoint desde un prompt.',
      traduccion: 'Traduce documentos de Word y emails directamente en la suite.',
      prompting: 'No aplica.',
      imagenes: 'Genera imagenes para presentaciones con Designer integrado.',
      estudio: 'Resume documentos academicos en Word y genera guias de estudio.',
      finanzas: 'Genera modelos financieros en Excel con formulas y graficos automaticos.',
      matematicas: 'Automatiza calculos en Excel con lenguaje natural.',
      arte: 'Diseno de presentaciones con estetica profesional en PowerPoint.',
      video: 'No genera video directamente.',
      audio: 'Transcripcion y resumen de reuniones de Teams.',
      legal: 'Redacta y revisa contratos directamente en Word con estilo juridico.',
      medicina: 'Resume historiales medicos en Word y genera informes clinicos.',
      productividad: 'La integracion de IA mas profunda en un ecosistema de productividad empresarial del mundo.',
      roleplay: 'No aplica.',
      escritura: 'Redacta y mejora documentos Word con sugerencias en contexto.',
      investigacion: 'Resume y analiza papers en Word. Genera reportes de investigacion.',
    },
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    company: 'Notion',
    description: 'IA integrada en Notion para gestionar proyectos, notas y documentos. Resume, traduce, mejora textos y genera contenido directamente en tu workspace.',
    categories: ['productividad', 'escritura', 'estudio', 'investigacion'],
    badges: ['especializado', 'mas-barato'],
    price: '$8/mes add-on sobre plan Notion',
    emoji: '📝',
    tier: 'A',
    reasonWhy: {
      coding: 'Genera documentacion tecnica y wikis de proyectos de forma automatica.',
      'ciencia-datos': 'No su especialidad principal.',
      marketing: 'Planifica campanas, genera briefs y organiza contenido en tu workspace.',
      traduccion: 'Traduce paginas y documentos de Notion al instante.',
      prompting: 'No aplica.',
      imagenes: 'No genera imagenes.',
      estudio: 'Transforma apuntes en resumenes, flashcards y guias de estudio desde Notion.',
      finanzas: 'Organiza y analiza datos financieros en bases de datos de Notion.',
      matematicas: 'No especializado.',
      arte: 'No aplica.',
      video: 'No genera video.',
      audio: 'No genera audio.',
      legal: 'Organiza contratos y documentos legales con busqueda semantica.',
      medicina: 'Gestiona notas clinicas y literatura medica en tu workspace personal.',
      productividad: 'El segundo cerebro con IA integrada. Sintetiza, resume y conecta toda tu informacion en un lugar.',
      roleplay: 'Gestiona wikis de worldbuilding y fichas de personajes de campanas.',
      escritura: 'Asistente de escritura integrado en tu flujo de notas y documentos.',
      investigacion: 'Organiza y sintetiza tu biblioteca de investigacion con busqueda semantica.',
    },
  },
  // ─── ESPECIALIZADOS ──────────────────────────────────────────────────────
  {
    id: 'harvey-ai',
    name: 'Harvey AI',
    company: 'Harvey',
    description: 'El LLM especializado en derecho usado por las 100 firmas legales mas grandes del mundo. Entrenado en millones de documentos juridicos.',
    categories: ['legal', 'investigacion', 'escritura'],
    badges: ['especializado', 'mejor-calidad'],
    price: 'Enterprise (por cotizacion)',
    emoji: '⚖️',
    tier: 'S',
    reasonWhy: {
      coding: 'No aplica.',
      'ciencia-datos': 'Analisis de grandes volumenes de documentos legales con IA.',
      marketing: 'No aplica.',
      traduccion: 'Traduccion juridica con terminologia legal correcta entre jurisdicciones.',
      prompting: 'No aplica.',
      imagenes: 'No aplica.',
      estudio: 'Preparacion para examenes de barra y casos practicos de derecho.',
      finanzas: 'Contratos financieros, M&A y documentacion de due diligence.',
      matematicas: 'No aplica.',
      arte: 'Propiedad intelectual, derechos de autor y contratos de licencia de arte.',
      video: 'Contratos de produccion y derechos de distribucion de video.',
      audio: 'Contratos musicales y derechos de autor en audio.',
      legal: 'El modelo definitivo para profesionales del derecho. Usado por Allen & Overy, A&O Shearman y las 100 firmas top globales.',
      medicina: 'Regulacion medica, contratos hospitalarios y compliance farmaceutico.',
      productividad: 'Automatiza la redaccion y revision de contratos a escala.',
      roleplay: 'No aplica.',
      escritura: 'Redaccion juridica precisa — contratos, memorandums y briefs legales.',
      investigacion: 'Due diligence, investigacion de precedentes y analisis regulatorio a gran escala.',
    },
  },
  {
    id: 'bloombergGPT',
    name: 'BloombergGPT',
    company: 'Bloomberg',
    description: 'LLM entrenado en 363B tokens de datos financieros de Bloomberg. Comprension nativa de mercados, instrumentos financieros y terminologia bursatil.',
    categories: ['finanzas', 'investigacion', 'ciencia-datos'],
    badges: ['especializado', 'mejor-calidad'],
    price: 'Bloomberg Terminal ($24,000/ano)',
    emoji: '📈',
    tier: 'S',
    reasonWhy: {
      coding: 'Genera codigo financiero (Python quant, R estadistico) con terminologia correcta.',
      'ciencia-datos': 'Analisis de series temporales financieras y modelado cuantitativo de mercados.',
      marketing: 'No aplica.',
      traduccion: 'No especializado.',
      prompting: 'No aplica.',
      imagenes: 'No aplica.',
      estudio: 'Preparacion para CFA, FRM y otras certificaciones financieras.',
      finanzas: 'El modelo definitivo para finanzas. Entrenado en datos de Bloomberg Terminal con comprension nativa de mercados.',
      matematicas: 'Modelos cuantitativos, calculo de derivados y matematica financiera avanzada.',
      arte: 'No aplica.',
      video: 'No aplica.',
      audio: 'No aplica.',
      legal: 'Contratos financieros, regulacion bancaria y compliance de valores.',
      medicina: 'No aplica.',
      productividad: 'Automatiza reportes financieros y analisis de cartera.',
      roleplay: 'No aplica.',
      escritura: 'Reportes de investigacion financiera y analisis de mercado profesionales.',
      investigacion: 'Investigacion financiera con acceso a datos historicos de Bloomberg.',
    },
  },
]

// Construir el mapa de modelos por categoria O(1) — js-index-maps
for (const model of ALL_MODELS) {
  for (const category of model.categories) {
    const existing = MODELS_BY_CATEGORY.get(category) ?? []
    MODELS_BY_CATEGORY.set(category, [...existing, model])
  }
}
